=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/build/schemaorg_apache_xmlbeans/src/adddef.xsd
<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema'
           targetNamespace='http://cl/bee/genfrmjava/adddef/schema'
                     xmlns='http://cl/bee/genfrmjava/adddef/schema'>

 <!-- ========================================================================================== ==
   == additional
   == ========================================================================================== -->

 <xsd:element name='additional'>

  <xsd:complexType>

   <xsd:sequence>
     <xsd:element ref='section' minOccurs='0' maxOccurs='unbounded'/>
   </xsd:sequence>

   <xsd:attribute name='system' type='xsd:string' use='required'/>
   <xsd:attribute name='form'   type='xsd:string' use='required'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == section
   == ========================================================================================== -->

 <xsd:element name='section'>

  <xsd:complexType>

    <xsd:sequence>
      <xsd:element ref='code'/>
    </xsd:sequence>

    <xsd:attribute name='name' type='xsd:string' use='required'/>
  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == code
   == ========================================================================================== -->

 <xsd:element name='code' type='xsd:string'/>

</xsd:schema>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/addit/addit_sgc_cfc_bu.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<additional xmlns        = "http://cl/bee/genfrmjava/adddef/schema"
      xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation = "http://cl/bee/genfrmjava/adddef/schema adddef.xsd"
      system             = "SGC"
      form               = "CFC">

  <!-- ========================================================================================== ==
    == DBC_GLS_ICLI
    == ========================================================================================== -->

  <section name="DBC_GLS_ICLI">

    <code><![CDATA[      *<<<< DBC_GLS_ICLI
           IF DBC-NUM-ICLI IN CFC-FLD > ZEROES
              MOVE DBC-NUM-ICLI IN CFC-FLD TO DBC-NUM-ICLI IN DBC
              MOVE DBC-IND-ICLI IN CFC-FLD TO DBC-IND-ICLI IN DBC
              MOVE DBC-GLS-ICLI IN CFC-FLD TO DBC-GLS-ICLI IN DBC
              MOVE 'DBC-IDC-ICLI'  TO FIO-AKEY
              MOVE FIO-GET-KEY TO FIO-CMND
              PERFORM SGC-FIO-DBC
              IF NOT FIO-STAT-OKS
                  MOVE 'SGC'        TO MSG-COD-SIST
                  MOVE 'CLI    NEX' TO MSG-COD-MENS
                  PERFORM GET-MSG
                  MOVE SPACES       TO FRM-GLS-NOMC IN CFC-FLD
                  MOVE MSG-GLS-DESC TO FRM-MENS
                  MOVE FRM-SUAR-MAL TO FRM-SUAR
                  GO TO FIN-VAL-DBC-GLS-ICLI
              ELSE
                  MOVE DBC-CIC-ICLI IN DBC TO SCR-CIC-ICLI
                  MOVE DBC-GLS-NOMC IN DBC TO CPT-STRN
                  PERFORM CPT-BLKS
                  MOVE CPT-STRN  TO FRM-GLS-NOMC IN CFC-FLD.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == FIN_PUT_RPR_CFC
    == ========================================================================================== -->

  <section name="FIN_PUT_RPR_CFC">

    <code><![CDATA[      *BUS-TAB busca glosa de codigo en tabla
           IF RPR-IND-ESTA IN CFC-FLD > SPACES
               MOVE 'SGC' TO TAB-COD-SIST
               MOVE 'EST ' TO TAB-COD-TTAB IN TAB
               MOVE RPR-IND-ESTA IN CFC-FLD TO TAB-COD-CTAB IN TAB
               PERFORM BUS-TAB
               MOVE TAB-GLS-DESC IN TAB TO
                    FRM-GLS-ESTA IN CFC-FLD
           ELSE
               MOVE SPACES TO FRM-GLS-ESTA IN CFC-FLD.
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == FIN_RPR_COD_TFRM
    == ========================================================================================== -->

  <section name="FIN_RPR_COD_TFRM">

    <code><![CDATA[      *<<<<
           IF RPR-COD-TFRM IN CFC-FLD NOT > SPACES
              GO TO  FIN-VAL-RPR-COD-TFRM.
      *VAL-COD Valida codigo de tabla
           MOVE 'SGC' TO TAB-COD-SIST.
           MOVE 'DRE' TO TAB-COD-TTAB IN TAB.
           MOVE RPR-COD-TFRM IN CFC-FLD TO TAB-COD-CTAB IN TAB.
           PERFORM VAL-COD.
           IF MSG-COD-MENS = 'COD    NEX' OR
              RPR-COD-TFRM IN CFC-FLD NOT > SPACES
               MOVE SPACES TO FRM-GLS-LDOC IN CFC-FLD
           ELSE
               MOVE TAB-GLS-DESC IN TAB TO
                    FRM-GLS-LDOC IN CFC-FLD.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == FIN_RPR_IND_ESTA
    == ========================================================================================== -->

  <section name="FIN_RPR_IND_ESTA">

    <code><![CDATA[      *<<<<
           IF RPR-IND-ESTA IN CFC-FLD NOT > SPACES
              GO TO FIN-VAL-RPR-IND-ESTA.
      *VAL-COD Valida codigo de tabla
           MOVE 'SGC' TO TAB-COD-SIST.
           MOVE 'EST' TO TAB-COD-TTAB IN TAB.
           MOVE RPR-IND-ESTA IN CFC-FLD TO TAB-COD-CTAB IN TAB.
           PERFORM VAL-COD.
           IF MSG-COD-MENS = 'COD    NEX' OR
              RPR-IND-ESTA IN CFC-FLD NOT > SPACES
               MOVE SPACES TO FRM-GLS-ESTA IN CFC-FLD
           ELSE
               MOVE TAB-GLS-DESC IN TAB TO
                    FRM-GLS-ESTA IN CFC-FLD.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    ==
    == ========================================================================================== -->

</additional>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/addit/addit_sgc_qre_bq.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<additional xmlns        = "http://cl/bee/genfrmjava/adddef/schema"
      xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation = "http://cl/bee/genfrmjava/adddef/schema adddef.xsd"
      system             = "SGC"
      form               = "QRE">

  <!-- ========================================================================================== ==
    == DBC_GLS_ICLI
    == ========================================================================================== -->

  <section name="DBC_GLS_ICLI">

    <code><![CDATA[      *<<<< DBC_GLS_ICLI
           IF DBC-NUM-ICLI IN QRE-FLD > ZEROES
              MOVE DBC-NUM-ICLI IN QRE-FLD TO DBC-NUM-ICLI IN DBC
              MOVE DBC-IND-ICLI IN QRE-FLD TO DBC-IND-ICLI IN DBC
              MOVE DBC-GLS-ICLI IN QRE-FLD TO DBC-GLS-ICLI IN DBC
              MOVE 'DBC-IDC-ICLI'  TO FIO-AKEY
              MOVE FIO-GET-KEY TO FIO-CMND
              PERFORM SGC-FIO-DBC
              IF NOT FIO-STAT-OKS
                  MOVE 'SGC'        TO MSG-COD-SIST
                  MOVE 'CLI    NEX' TO MSG-COD-MENS
                  PERFORM GET-MSG
                  MOVE SPACES       TO FRM-GLS-RZNS IN QRE-FLD
                  MOVE MSG-GLS-DESC TO FRM-MENS
                  MOVE FRM-SUAR-MAL TO FRM-SUAR
                  GO TO FIN-VAL-DBC-GLS-ICLI
              ELSE
                  MOVE DBC-GLS-NOMC IN DBC TO CPT-STRN
                  PERFORM CPT-BLKS
                  MOVE CPT-STRN  TO FRM-GLS-RZNS IN QRE-FLD
                  MOVE DBC-CAI-ICLI IN DBC TO SCR-CAI-ICLI
                  MOVE DBC-IIC-ICLI IN DBC TO SCR-IIC-ICLI.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == DBC_NUM_ICLI
    == ========================================================================================== -->

  <section name="DBC_NUM_ICLI">

    <code><![CDATA[      *<<<< DBC_NUM_ICLI
           IF DBC-NUM-ICLI IN QRE-FLD NOT > ZEROES
               PERFORM ERR-GLS
               GO TO FIN-VAL-DBC-NUM-ICLI.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == FRM_IND_INVR
    == ========================================================================================== -->

  <section name="FRM_IND_INVR">

    <code><![CDATA[      *<<<< FRM_IND_INVR
           IF FRM-IND-INVR IN QRE-FLD NOT > SPACES
              MOVE 'N' TO FRM-IND-INVR IN QRE-FLD.
           IF FRM-IND-INVR IN QRE-FLD = 'N'
              GO TO FIN-VAL-FRM-IND-INVR.

           IF REC-COD-TREC IN QRE-FLD NOT > SPACES
              MOVE 'SGC'        TO MSG-COD-SIST
              MOVE 'INVR   INV' TO MSG-COD-MENS
              PERFORM GET-MSG
              MOVE MSG-GLS-DESC TO FRM-MENS
              MOVE FRM-SUAR-MAL TO FRM-SUAR
              GO TO FIN-VAL-FRM-IND-INVR.

           MOVE 'SGC'                   TO TAB-COD-SIST FIO-SIST.
           MOVE 'REC'                   TO TAB-COD-TTAB IN TAB.
           MOVE REC-COD-TREC IN QRE-FLD TO TAB-COD-CTAB IN TAB.
           MOVE FIO-GET-KEY TO FIO-CMND.
           PERFORM GNS-FIO-TAB.
           IF NOT FIO-STAT-OKS
              MOVE SPACES TO WSS-COD-TREC-INV IN WSS-VARI
              GO TO FIN-VAL-FRM-IND-INVR.
           MOVE TAB-GLS-DAT1 IN TAB TO WSS-COD-TREC-INV1 IN WSS-VARI.
           MOVE SPACES              TO WSS-COD-TREC-INV2 IN WSS-VARI.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == FRM_IND_TCON
    == ========================================================================================== -->

  <section name="FRM_IND_TCON">

    <code><![CDATA[      *<<<< FRM_IND_TCON
           IF FRM-IND-TCON IN QRE-FLD NOT > SPACES
              MOVE 'N' TO FRM-IND-TCON IN QRE-FLD.
      *MHM-INI 23-AGO-2016 ARTICULO 85
           MOVE REC-COD-TREC IN QRE-FLD TO WSS-COD-TR02 IN WSS-ART85.
           IF (FRM-IND-TCON IN QRE-FLD = 'A' OR 'R') AND
              WSS-COD-TR02 IN WSS-ART85 NOT =
                                       WSS-COD-TRCD IN WSS-ART85 AND
              WSS-COD-TR02 IN WSS-ART85 NOT =
                                       WSS-COD-TRDC IN WSS-ART85
               MOVE 'SGC'         TO MSG-COD-SIST
               MOVE 'TCONTRECINV' TO MSG-COD-MENS
               PERFORM GET-MSG
               MOVE MSG-GLS-DESC TO FRM-MENS
               MOVE FRM-SUAR-MAL TO FRM-SUAR
               GO TO FIN-VAL-FRM-IND-TCON.

      *MHM-FIN 23-AGO-2016 ARTICULO 85
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == SETTAG
    == ========================================================================================== -->

  <section name="SETTAG">

    <code><![CDATA[]]></code>

  </section>

  <!-- ========================================================================================== ==
    ==
    == ========================================================================================== -->

</additional>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/addit/addit_sgc_dir_bq.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<additional xmlns        = "http://cl/bee/genfrmjava/adddef/schema"
      xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation = "http://cl/bee/genfrmjava/adddef/schema adddef.xsd"
      system             = "SGC"
      form               = "DIR">

  <!-- ========================================================================================== ==
    == FIN_KEY_DBC_DIR
    == ========================================================================================== -->

  <section name="FIN_KEY_DBC_DIR">

    <code><![CDATA[      *<<<< FIN_KEY_DBC_DIR
           MOVE DBC-NUM-TDIR IN DIR-FLD TO DBC-NUM-TDIR IN DBC.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == FIN_PUT_DBC_DIR
    == ========================================================================================== -->

  <section name="FIN_PUT_DBC_DIR">

    <code><![CDATA[      *<<<< FIN_PUT_DBC_DIR
           MOVE DBC-GLS-NOMC IN DBC TO CPT-STRN.
           PERFORM CPT-BLKS.
           MOVE CPT-STRN TO DBC-GLS-NOMC IN DIR-FLD.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == FIN_VAL_CON_KEY_DIR
    == ========================================================================================== -->

  <section name="FIN_VAL_CON_KEY_DIR">

    <code><![CDATA[      *<<<< FIN_VAL_CON_KEY_DIR
           IF DBC-GLS-NOMC IN DIR-FLD NOT > SPACES AND
              DBC-NUM-ICLI IN DIR-FLD NOT > ZEROES
      *GET-MSG Busca mensaje en tabla
               MOVE 'GNS' TO MSG-COD-SIST
               MOVE 'VALCONKEY' TO MSG-COD-MENS
               PERFORM GET-MSG
               MOVE MSG-GLS-DESC TO FRM-MENS
               MOVE FRM-SUAR-MAL TO FRM-SUAR
               GO TO FIN-VAL-CON-KEY-DIR.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == INI_VAL_CON_KEY_DIR
    == ========================================================================================== -->

  <section name="INI_VAL_CON_KEY_DIR">

    <code><![CDATA[      *<<<< INI_VAL_CON_KEY_DIR
           IF FRM-FFLD = FRM-FFLD-PF7 OR FRM-FFLD-PF8
               GO TO FIN-VAL-CON-KEY-DIR.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == INI_VAL_FLD_DIR
    == ========================================================================================== -->

  <section name="INI_VAL_FLD_DIR">

    <code><![CDATA[]]></code>

  </section>

  <!-- ========================================================================================== ==
    == PGM_PER
    == ========================================================================================== -->

  <section name="PGM_PER">

    <code><![CDATA[]]></code>

  </section>

  <!-- ========================================================================================== ==
    == RCD_GLS_DIRE
    == ========================================================================================== -->

  <section name="RCD_GLS_DIRE">

    <code><![CDATA[      *<<<< RCD_GLS_DIRE
           IF RCD-GLS-DIRE IN DIR-FLD NOT > SPACES
               PERFORM ERR-GLS.
      *>>>>
      *FSA-AFRI-INI/15042003
           MOVE RCD-GLS-DIRE IN DIR-FLD TO VCL-STRN.
           MOVE 'DIR'                   TO VCL-CMPO.
           MOVE 'N'                     TO VCL-ICOR.
           MOVE 60                      TO VCL-LENG.
           PERFORM SGC-BUS-VCL.
           IF VCL-IERR = 'S'
               MOVE 'SGC'          TO MSG-COD-SIST
               MOVE 'DIRECHARNEX'  TO MSG-COD-MENS
               PERFORM GET-MSG
               MOVE MSG-GLS-DESC TO FRM-MENS
               MOVE FRM-SUAR-MAL TO FRM-SUAR
               GO TO FIN-VAL-RCD-GLS-DIRE.
      *FSA-AFRI-FIN/15042003
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == VAL_CON_FLD_DIR
    == ========================================================================================== -->

  <section name="VAL_CON_FLD_DIR">

    <code><![CDATA[]]></code>

  </section>

  <!-- ========================================================================================== ==
    ==
    == ========================================================================================== -->

</additional>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/addit/addit_sgc_cco_bu.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<additional xmlns        = "http://cl/bee/genfrmjava/adddef/schema"
      xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation = "http://cl/bee/genfrmjava/adddef/schema adddef.xsd"
      system             = "SGC"
      form               = "CCO">

  <!-- ========================================================================================== ==
    == FIN_PUT_DBC_CCO
    == ========================================================================================== -->

  <section name="FIN_PUT_DBC_CCO">

    <code><![CDATA[      *<<<< FIN_PUT_DBC_CCO
           MOVE DBC-GLS-NOMC IN DBC TO CPT-STRN.
           PERFORM CPT-BLKS.
           MOVE CPT-STRN TO DBC-GLS-NOMC IN CCO-FLD.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == FIN_PUT_RCO_CCO
    == ========================================================================================== -->

  <section name="FIN_PUT_RCO_CCO">

    <code><![CDATA[      *<<<< FIN_PUT_RCO_CCO
      *     IF NOT FIO-STAT-OKS
      *         MOVE ZEROES TO FRM-NUM-AANT IN CCO-FLD.
      *         MOVE ZEROES TO FRM-NUM-MANT IN CCO-FLD.
      *         MOVE ZEROES TO FRM-FEC-FUOB IN CCO-FLD.
      *         GO TO FIN-PUT-RCO-CCO.
      *     PERFORM GET-FHOY.
      *     IF FEC-MHOY NOT < DBC-NUM-MIOP IN DBC
      *         SUBTRACT DBC-NUM-AIOP IN DBC FROM FEC-AHOY
      *           GIVING FRM-NUM-AANT IN CCO-FLD
      *         SUBTRACT DBC-NUM-MIOP IN DBC FROM FEC-MHOY
      *           GIVING FRM-NUM-MANT IN CCO-FLD
      *     ELSE
      *         SUBTRACT DBC-NUM-AIOP IN DBC FROM FEC-AHOY
      *           GIVING FRM-NUM-AANT IN CCO-FLD
      *         SUBTRACT 1 FROM FRM-NUM-AANT IN CCO-FLD
      *         COMPUTE FRM-NUM-MANT IN CCO-FLD = FEC-MHOY +
      *                            12 - DBC-NUM-MIOP IN DBC.
      **    IF DBC-NUM-OVIG IN DBC NOT = ZEROES
      **       MOVE ZEROES TO FRM-FEC-FUOB IN CCO-FLD
      **    ELSE
      *        MOVE DBC-NUM-STOP IN DBC TO FRM-NUM-SUOB IN CCO-FLD.
      *        MOVE DBC-NUM-ATOP IN DBC TO FRM-NUM-AUOB IN CCO-FLD.
      *        MOVE DBC-NUM-MTOP IN DBC TO FRM-NUM-MUOB IN CCO-FLD.
      *        MOVE DBC-NUM-DTOP IN DBC TO FRM-NUM-DUOB IN CCO-FLD.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == INI_VAL_CON_KEY_CCO
    == ========================================================================================== -->

  <section name="INI_VAL_CON_KEY_CCO">

    <code><![CDATA[      *<<<< INI_VAL_CON_KEY_CCO
           IF FRM-FFLD = FRM-FFLD-PF7 OR FRM-FFLD-PF8
               GO TO FIN-VAL-CON-KEY-CCO.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == NOT PGM_PER
    == ========================================================================================== -->

  <section name="NOT PGM_PER">

    <code><![CDATA[]]></code>

  </section>

  <!-- ========================================================================================== ==
    == NOT PGM_PER AND DBC_GLS_ICLI
    == ========================================================================================== -->

  <section name="NOT PGM_PER AND DBC_GLS_ICLI" concatenate="1">

    <code><![CDATA[      *<<<< DBC_GLS_ICLI
            MOVE DBC-GLS-ICLI IN CCO-FLD TO IDC-GLS-RUTV.
            PERFORM VAL-GLS.
            MOVE IDC-GLS-RUTV TO DBC-GLS-ICLI IN CCO-FLD.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == NOT PGM_PER AND DBC_IND_ICLI
    == ========================================================================================== -->

  <section name="NOT PGM_PER AND DBC_IND_ICLI" concatenate="1">

    <code><![CDATA[      *<<<< DBC_IND_ICLI
            MOVE DBC-IND-ICLI IN CCO-FLD TO IDC-IND-RUTV.
            PERFORM VAL-IDC.
            MOVE IDC-IND-RUTV TO DBC-IND-ICLI IN CCO-FLD.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == NOT PGM_PER AND DBC_VRF_ICLI
    == ========================================================================================== -->

  <section name="NOT PGM_PER AND DBC_VRF_ICLI" concatenate="1">

    <code><![CDATA[      *<<<< DBC_VRF_ICLI
           MOVE IDC-ZERO-S TO IDC-ZERO.
           MOVE DBC-NUM-ICLI IN CCO-FLD TO IDC-NUM-RUTV.
           MOVE DBC-VRF-ICLI IN CCO-FLD TO IDC-VRF-RUTV.
           PERFORM VAL-RUT.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == NOT PGM_PER AND INI_PUT_DBC_CCO
    == ========================================================================================== -->

  <section name="NOT PGM_PER AND INI_PUT_DBC_CCO" concatenate="1">

    <code><![CDATA[      *<<<< INI_PUT_DBC_CCO
           IF PGM-STAT-DBC-NUL
               GO TO FIN-PUT-DBC-CCO.
           IF NOT PGM-STAT-DBC-OKS
               PERFORM CLR-DBC-CCO
               GO TO FIN-PUT-DBC-CCO.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == NOT PGM_PER AND INI_PUT_RCO_CCO
    == ========================================================================================== -->

  <section name="NOT PGM_PER AND INI_PUT_RCO_CCO" concatenate="1">

    <code><![CDATA[      *<<<< INI_PUT_RCO_CCO
           IF PGM-STAT-RCO-NUL
               GO TO FIN-PUT-RCO-CCO.
           IF NOT PGM-STAT-RCO-OKS
               PERFORM CLR-RCO-CCO
               GO TO FIN-PUT-RCO-CCO.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == NOT PGM_PER$1
    == ========================================================================================== -->

  <section name="NOT PGM_PER$1">

    <code><![CDATA[]]></code>

  </section>

  <!-- ========================================================================================== ==
    == NOT PGM_PER$2
    == ========================================================================================== -->

  <section name="NOT PGM_PER$2">

    <code><![CDATA[]]></code>

  </section>

  <!-- ========================================================================================== ==
    == NOT PGM_PER$3
    == ========================================================================================== -->

  <section name="NOT PGM_PER$3">

    <code><![CDATA[]]></code>

  </section>

  <!-- ========================================================================================== ==
    == NOT PGM_PER$4
    == ========================================================================================== -->

  <section name="NOT PGM_PER$4">

    <code><![CDATA[]]></code>

  </section>

  <!-- ========================================================================================== ==
    == NOT PGM_PER$5
    == ========================================================================================== -->

  <section name="NOT PGM_PER$5">

    <code><![CDATA[]]></code>

  </section>

  <!-- ========================================================================================== ==
    == NOT PGM_PER$6
    == ========================================================================================== -->

  <section name="NOT PGM_PER$6">

    <code><![CDATA[]]></code>

  </section>

  <!-- ========================================================================================== ==
    == NOT PGM_PER$7
    == ========================================================================================== -->

  <section name="NOT PGM_PER$7">

    <code><![CDATA[]]></code>

  </section>

  <!-- ========================================================================================== ==
    ==
    == ========================================================================================== -->

</additional>
