=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/build/schemaorg_apache_xmlbeans/src/adddef.xsd
<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema'
           targetNamespace='http://cl/bee/genfrmjava/adddef/schema'
                     xmlns='http://cl/bee/genfrmjava/adddef/schema'>

 <!-- ========================================================================================== ==
   == additional
   == ========================================================================================== -->

 <xsd:element name='additional'>

  <xsd:complexType>

   <xsd:sequence>
     <xsd:element ref='section' minOccurs='0' maxOccurs='unbounded'/>
   </xsd:sequence>

   <xsd:attribute name='system' type='xsd:string' use='required'/>
   <xsd:attribute name='form'   type='xsd:string' use='required'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == section
   == ========================================================================================== -->

 <xsd:element name='section'>

  <xsd:complexType>

    <xsd:sequence>
      <xsd:element ref='code'/>
    </xsd:sequence>

    <xsd:attribute name='name' type='xsd:string' use='required'/>
  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == code
   == ========================================================================================== -->

 <xsd:element name='code' type='xsd:string'/>

</xsd:schema>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/addit/addit_dap_ccc_bu.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<additional xmlns        = "http://cl/bee/genfrmjava/adddef/schema"
      xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation = "http://cl/bee/genfrmjava/adddef/schema adddef.xsd"
      system             = "DAP"
      form               = "CCC">

  <!-- ========================================================================================== ==
    == DBC_GLS_ICLI
    == ========================================================================================== -->

  <section name="DBC_GLS_ICLI">

    <code><![CDATA[      *<<<< DBC_GLS_ICLI
           IF DBC-NUM-ICLI IN CCC-FLD NOT > ZEROES
           IF DBC-GLS-NOMC IN CCC-FLD > SPACES
      *NOM-CLI Busca Cliente por medio del Nombre
               MOVE DBC-GLS-NOMC IN CCC-FLD TO STR-GLS-GSTR
               PERFORM STR-UNS
               MOVE STR-GLS-FUNS IN STR-VARI(1) TO DBC-GLS-APAT IN DBC
               MOVE STR-GLS-FUNS IN STR-VARI(2) TO DBC-GLS-AMAT IN DBC
               MOVE STR-GLS-FUNS IN STR-VARI(3) TO DBC-GLS-NOMB IN DBC
               MOVE 'DBC-GLS-NOMC' TO FIO-AKEY
               MOVE FIO-GET-NLS    TO FIO-CMND
               PERFORM SGC-FIO-DBC
               IF NOT FIO-STAT-OKS
                   MOVE 'DAP'        TO MSG-COD-SIST
                   MOVE 'CLICCC NEX' TO MSG-COD-MENS
                   PERFORM GET-MSG
                   MOVE MSG-GLS-DESC IN MSG TO FRM-MENS
                   MOVE ZEROES       TO DBC-NUM-ICLI IN CCC-FLD
                   MOVE SPACES       TO DBC-VRF-ICLI IN CCC-FLD
                   MOVE SPACES       TO DBC-IND-ICLI IN CCC-FLD
                   MOVE SPACES       TO DBC-GLS-ICLI IN CCC-FLD
                   MOVE FRM-SUAR-MAL TO FRM-SUAR
               ELSE
                   MOVE DBC-NUM-ICLI IN DBC TO
                        DBC-NUM-ICLI IN CCC-FLD
                   MOVE DBC-VRF-ICLI IN DBC TO
                        DBC-VRF-ICLI IN CCC-FLD
                   MOVE DBC-IND-ICLI IN DBC TO
                        DBC-IND-ICLI IN CCC-FLD
                   MOVE DBC-GLS-ICLI IN DBC TO
                        DBC-GLS-ICLI IN CCC-FLD

                   MOVE SPACES TO MSG-COD-MENS
                   MOVE '00'         TO PGM-STAT-DBC
                   MOVE DBC-GLS-NOMC IN DBC TO CPT-STRN
                   PERFORM CPT-BLKS
                   MOVE CPT-STRN            TO DBC-GLS-NOMC IN DBC
                   PERFORM BKP-CIC-CLI

                   IF DBC-COD-TICL IN DBC = 'EE' OR
                      DBC-COD-TICL IN DBC = 'FI'
                       MOVE WSS-IDN-SIST            TO USP-SISTEMA
                       MOVE SPACES                  TO USP-PERMISO
                       MOVE 'DAP'                   TO USP-GRUPO
                       MOVE SCR-USER                TO USP-USUARIO
      * CDC = CONSULTA DATO COLBORADOR
                       MOVE 'DAPPQCCC/CDC'          TO USP-STRING
                       PERFORM USPC107
                       IF USP-PERMISO NOT = 'P'
                           MOVE 'DAP'          TO MSG-COD-SIST
                           MOVE 'USRDAPNOCDC'  TO MSG-COD-MENS
                           PERFORM GET-MSG
                           MOVE MSG-GLS-DESC   TO FRM-MENS
                           MOVE MSG-GLS-DESC IN MSG TO FRM-MENS
                           MOVE FRM-SUAR-MAL TO FRM-SUAR
                           GO TO FIN-VAL-DBC-GLS-ICLI.

           IF FRM-SUAR = FRM-SUAR-MAL
                 GO TO FIN-VAL-DBC-GLS-ICLI.

]]></code>

  </section>

  <!-- ========================================================================================== ==
    == DBC_VRF_ICLI
    == ========================================================================================== -->

  <section name="DBC_VRF_ICLI">

    <code><![CDATA[      *<<<< DBC_VRF_ICLI
           IF FRM-SUAR = FRM-SUAR-MAL
                 GO TO FIN-VAL-DBC-VRF-ICLI.
           IF DBC-NUM-ICLI IN CCC-FLD > ZEROES
      *IDC-CLI Busca Cliente por medio de IdC
               MOVE DBC-NUM-ICLI IN CCC-FLD TO DBC-NUM-ICLI IN DBC
               MOVE DBC-IND-ICLI IN CCC-FLD TO DBC-IND-ICLI IN DBC
               MOVE DBC-GLS-ICLI IN CCC-FLD TO DBC-GLS-ICLI IN DBC
               MOVE 'DBC-IDC-ICLI' TO FIO-AKEY
               MOVE FIO-GET-KEY    TO FIO-CMND
               PERFORM SGC-FIO-DBC
               MOVE FIO-STAT         TO PGM-STAT-DBC
               IF NOT FIO-STAT-OKS
                   MOVE 'DAP'        TO MSG-COD-SIST
                   MOVE 'CLICCC NEX' TO MSG-COD-MENS
                   PERFORM GET-MSG
                   MOVE MSG-GLS-DESC IN MSG TO FRM-MENS
                   MOVE FRM-SUAR-MAL TO FRM-SUAR
               ELSE
                   MOVE SPACES TO MSG-COD-MENS
                   MOVE DBC-GLS-NOMC IN DBC TO CPT-STRN
                   PERFORM CPT-BLKS
                   MOVE CPT-STRN            TO DBC-GLS-NOMC IN DBC
                   PERFORM BKP-CIC-CLI
      *ISP-INI Transacciones Lentas
                   IF SCR-CNAL NOT = WSS-CT-CNAL-100 AND
                      SCR-CNAL NOT = WSS-CT-CNAL-110
      *ISP-FIN Transacciones Lentas
                   IF DBC-COD-TICL IN DBC = 'EE' OR
                      DBC-COD-TICL IN DBC = 'FI'
                       MOVE WSS-IDN-SIST            TO USP-SISTEMA
                       MOVE SPACES                  TO USP-PERMISO
                       MOVE 'DAP'                   TO USP-GRUPO
                       MOVE SCR-USER                TO USP-USUARIO
      * CDC = CONSULTA DATO COLBORADOR
                       MOVE 'DAPPQCCC/CDC'          TO USP-STRING
                       PERFORM USPC107
                       IF USP-PERMISO NOT = 'P'
                           MOVE 'DAP'          TO MSG-COD-SIST
                           MOVE 'USRDAPNOCDC'  TO MSG-COD-MENS
                           PERFORM GET-MSG
                           MOVE MSG-GLS-DESC   TO FRM-MENS
                           MOVE MSG-GLS-DESC IN MSG TO FRM-MENS
                           MOVE FRM-SUAR-MAL TO FRM-SUAR
                           GO TO FIN-VAL-DBC-VRF-ICLI.

           IF FRM-SUAR = FRM-SUAR-MAL
                 GO TO FIN-VAL-DBC-VRF-ICLI.

]]></code>

  </section>

  <!-- ========================================================================================== ==
    == FIN_PRO_AKY_CCC
    == ========================================================================================== -->

  <section name="FIN_PRO_AKY_CCC">

    <code><![CDATA[      *<<<<
           MOVE FRM-CPIM-AEY TO DBC-IND-ICLI-ATR IN CCC-FLD.
           MOVE FRM-CPIM-AEY TO DBC-GLS-ICLI-ATR IN CCC-FLD.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == FIN_UNP_AKY_CCC
    == ========================================================================================== -->

  <section name="FIN_UNP_AKY_CCC">

    <code><![CDATA[      *<<<<
           MOVE FRM-CPIM-UBY TO DBC-IND-ICLI-ATR.
           MOVE FRM-CPIM-UBY TO DBC-GLS-ICLI-ATR.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == SETTAG
    == ========================================================================================== -->

  <section name="SETTAG">

    <code><![CDATA[]]></code>

  </section>

  <!-- ========================================================================================== ==
    ==
    == ========================================================================================== -->

</additional>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/addit/addit_sgc_cca_bu.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<additional xmlns        = "http://cl/bee/genfrmjava/adddef/schema"
      xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation = "http://cl/bee/genfrmjava/adddef/schema adddef.xsd"
      system             = "SGC"
      form               = "CCA">

  <!-- ========================================================================================== ==
    == CAC_COD_CPTO
    == ========================================================================================== -->

  <section name="CAC_COD_CPTO">

    <code><![CDATA[      *<<<< CAC_COD_CPTO
           IF CAC-COD-CPTO IN CCA-FLD NOT > SPACES
              GO TO FIN-VAL-CAC-COD-CPTO.

      *VAL-COD Valida codigo de tabla
           MOVE 'TAB'                   TO TAB-COD-SIST.
           MOVE 'PSC'                   TO TAB-COD-TTAB IN TAB.
           MOVE CAC-COD-CPTO IN CCA-FLD TO TAB-COD-CTAB IN TAB.
           PERFORM VAL-COD.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == CAC_IND_VIGE
    == ========================================================================================== -->

  <section name="CAC_IND_VIGE">

    <code><![CDATA[      *<<<< CAC_IND_VIGE
           IF CAC-IND-VIGE IN CCA-FLD NOT > SPACES
              GO TO FIN-VAL-CAC-IND-VIGE.

      *VAL-COD Valida codigo de tabla
           MOVE 'TAB'                   TO TAB-COD-SIST.
           MOVE 'VIG'                   TO TAB-COD-TTAB IN TAB.
           MOVE CAC-IND-VIGE IN CCA-FLD TO TAB-COD-CTAB IN TAB.
           PERFORM VAL-COD.
           IF MSG-COD-MENS = 'COD    NEX' OR 'COD    NVG'
              MOVE MSG-GLS-DESC TO FRM-MENS
              MOVE FRM-SUAR-MAL TO FRM-SUAR.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == DBC_GLS_ICLI
    == ========================================================================================== -->

  <section name="DBC_GLS_ICLI">

    <code><![CDATA[      *<<<< DBC_GLS_ICLI
           IF DBC-NUM-ICLI IN CCA-FLD > ZEROES
              MOVE DBC-NUM-ICLI IN CCA-FLD TO DBC-NUM-ICLI IN DBC
              MOVE DBC-IND-ICLI IN CCA-FLD TO DBC-IND-ICLI IN DBC
              MOVE DBC-GLS-ICLI IN CCA-FLD TO DBC-GLS-ICLI IN DBC
              MOVE 'DBC-IDC-ICLI'  TO FIO-AKEY
              MOVE FIO-GET-KEY TO FIO-CMND
              PERFORM SGC-FIO-DBC
              IF NOT FIO-STAT-OKS
                  MOVE 'SGC'        TO MSG-COD-SIST
                  MOVE 'CLI    NEX' TO MSG-COD-MENS
                  PERFORM GET-MSG
                  MOVE MSG-GLS-DESC TO FRM-MENS
                  MOVE FRM-SUAR-MAL TO FRM-SUAR
                  GO TO FIN-VAL-DBC-GLS-ICLI
              ELSE
                 MOVE DBC-NUM-ICLI IN DBC TO WSS-NUM-ICLI IN WSS-VARI
                 MOVE DBC-IND-ICLI IN DBC TO WSS-IND-ICLI IN WSS-VARI
                 MOVE DBC-GLS-ICLI IN DBC TO WSS-GLS-ICLI IN WSS-VARI
                 MOVE DBC-VRF-ICLI IN DBC TO WSS-VRF-ICLI IN WSS-VARI
                 MOVE DBC-CAI-ICLI IN DBC TO WSS-CAI-ICLI IN WSS-VARI
                 MOVE DBC-IIC-ICLI IN DBC TO WSS-IIC-ICLI IN WSS-VARI
                 MOVE DBC-CAI-ICLI IN DBC TO SCR-CAI-ICLI
                 MOVE DBC-IIC-ICLI IN DBC TO SCR-IIC-ICLI.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == DBC_NUM_ICLI
    == ========================================================================================== -->

  <section name="DBC_NUM_ICLI">

    <code><![CDATA[      *<<<< DBC_NUM_ICLI
           IF DBC-NUM-ICLI IN CCA-FLD NOT > ZEROES
               MOVE SPACES TO SCR-CAI-ICLI IN SCR-VARI
               MOVE SPACES TO SCR-IIC-ICLI IN SCR-VARI.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == FIN_FST_KEY_CCA
    == ========================================================================================== -->

  <section name="FIN_FST_KEY_CCA">

    <code><![CDATA[      *<<<< FIN_FST_KEY_CCA
           MOVE -1 TO CAC-COD-CPTO-LEN IN CCA-FLD.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == INI_CAC_FEC_FINI
    == ========================================================================================== -->

  <section name="INI_CAC_FEC_FINI">

    <code><![CDATA[      *<<<< INI_CAC_FEC_FINI
           MOVE FEC-CHOY-N  TO FEC-CHOY.
           MOVE FEC-VHBL-N TO FEC-VHBL.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == INI_CAC_HRA_HINI
    == ========================================================================================== -->

  <section name="INI_CAC_HRA_HINI">

    <code><![CDATA[           IF CAC-HRA-HINI IN CCA-FLD NOT > ZEROES
              MOVE ZEROES TO CAC-HRA-HINI IN CCA-FLD
              GO TO FIN-VAL-CAC-HRA-HINI.
           IF CAC-HRA-HINI IN CCA-FLD > 235959
              MOVE 'SGC'          TO MSG-COD-SIST
              MOVE 'HRAINV      ' TO MSG-COD-MENS
              PERFORM GET-MSG
              MOVE MSG-GLS-DESC TO FRM-MENS
              MOVE FRM-SUAR-MAL TO FRM-SUAR
              GO TO FIN-VAL-CAC-HRA-HINI.
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == INI_FRM_FEC_INIS
    == ========================================================================================== -->

  <section name="INI_FRM_FEC_INIS">

    <code><![CDATA[      *<<<<
           MOVE FEC-CHOY-N TO FEC-CHOY.
           MOVE FEC-VHBL-N TO FEC-VHBL.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == INI_FRM_HRA_INIS
    == ========================================================================================== -->

  <section name="INI_FRM_HRA_INIS">

    <code><![CDATA[           IF FRM-HRA-INIS IN CCA-FLD > 235959
              MOVE 'SGC'          TO MSG-COD-SIST
              MOVE 'HRAINV      ' TO MSG-COD-MENS
              PERFORM GET-MSG
              MOVE MSG-GLS-DESC TO FRM-MENS
              MOVE FRM-SUAR-MAL TO FRM-SUAR
              GO TO FIN-VAL-FRM-HRA-INIS.
]]></code>

  </section>

  <!-- ========================================================================================== ==
    ==
    == ========================================================================================== -->

</additional>
