=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/build/schemaorg_apache_xmlbeans/src/adddef.xsd
<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema'
           targetNamespace='http://cl/bee/genfrmjava/adddef/schema'
                     xmlns='http://cl/bee/genfrmjava/adddef/schema'>

 <!-- ========================================================================================== ==
   == additional
   == ========================================================================================== -->

 <xsd:element name='additional'>

  <xsd:complexType>

   <xsd:sequence>
     <xsd:element ref='section' minOccurs='0' maxOccurs='unbounded'/>
   </xsd:sequence>

   <xsd:attribute name='system' type='xsd:string' use='required'/>
   <xsd:attribute name='form'   type='xsd:string' use='required'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == section
   == ========================================================================================== -->

 <xsd:element name='section'>

  <xsd:complexType>

    <xsd:sequence>
      <xsd:element ref='code'/>
    </xsd:sequence>

    <xsd:attribute name='name' type='xsd:string' use='required'/>
  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == code
   == ========================================================================================== -->

 <xsd:element name='code' type='xsd:string'/>

</xsd:schema>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/addit/addit_col_dlc_bu.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<additional xmlns        = "http://cl/bee/genfrmjava/adddef/schema"
      xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation = "http://cl/bee/genfrmjava/adddef/schema adddef.xsd"
      system             = "COL"
      form               = "DLC">

  <!-- ========================================================================================== ==
    == DBC_NUM_ICLI
    == ========================================================================================== -->

  <section name="DBC_NUM_ICLI" concatenate="1">

    <code><![CDATA[      *<<<< DBC_NUM_ICLI
           IF DBC-NUM-ICLI IN DLC-FLD NOT > ZEROES
               IF DBC-IND-ICLI IN DLC-FLD NOT = 'M'
                   MOVE SPACES TO DBC-VRF-ICLI IN DLC-FLD
                                  DBC-IND-ICLI IN DLC-FLD
                                  DBC-GLS-ICLI IN DLC-FLD
                                  GO TO FIN-VAL-DBC-NUM-ICLI
               ELSE
                   MOVE SPACES TO DBC-VRF-ICLI IN DLC-FLD
                                  DBC-GLS-ICLI IN DLC-FLD
                                  GO TO FIN-VAL-DBC-NUM-ICLI
           ELSE
               IF DBC-IND-ICLI IN DLC-FLD = 'M'
                   MOVE 'SGC'        TO MSG-COD-SIST
                   MOVE 'INDNUMICLII' TO MSG-COD-MENS
                   PERFORM GET-MSG
                   MOVE MSG-GLS-DESC TO FRM-MENS
                   MOVE FRM-SUAR-MAL TO FRM-SUAR.
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == DBC_NUM_ICLI AND PGM_BU
    == ========================================================================================== -->

  <section name="DBC_NUM_ICLI AND PGM_BU" concatenate="2">

    <code><![CDATA[
      * RBG/INI/17-ABR-1997
           IF SCR-CMND = 'ING' OR 'MOD'
      *IDC-CLI Busca Cliente por medio de IdC.
           MOVE DBC-NUM-ICLI IN DLC-FLD TO DBC-NUM-ICLI IN DBC
           MOVE DBC-IND-ICLI IN DLC-FLD TO DBC-IND-ICLI IN DBC
           MOVE DBC-GLS-ICLI IN DLC-FLD TO DBC-GLS-ICLI IN DBC
           MOVE 'DBC-IDC-ICLI' TO FIO-AKEY
           MOVE FIO-GET-KEY TO FIO-CMND
           PERFORM SGC-FIO-DBC
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == DBC_NUM_ICLI AND PGM_BU AND PGM_BX
    == ========================================================================================== -->

  <section name="DBC_NUM_ICLI AND PGM_BU AND PGM_BX" concatenate="3">

    <code><![CDATA[      *AFRI-INI/SEP2005
               IF SCR-HDR-MRCA = 'BCS'
                   MOVE 'COL'          TO MSG-COD-SIST
                   MOVE 'DLC    NODBC' TO MSG-COD-MENS IN MSG
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == DBC_NUM_ICLI AND PGM_BU$1
    == ========================================================================================== -->

  <section name="DBC_NUM_ICLI AND PGM_BU$1" concatenate="4">

    <code><![CDATA[           IF FIO-STAT-OKS
      * Si RUT cliente > 50.000.000 no validar Fecha Nacimiento.
                   IF DBC-NUM-ICLI IN DBC < WSS-NUM-ICLI IN WSS-VARI
                      AND DBC-IND-TICL IN DBC = 'P'
                       MOVE DBC-CIC-ICLI IN DBC TO DCP-CIC-ICLI IN DCP
                       MOVE FIO-GET-KEY TO FIO-CMND
                       PERFORM SGC-FIO-DCP
                       IF FIO-STAT-OKS
                           IF DCP-FEC-FNAC IN DCP NOT > ZEROES
                               MOVE 'COL'          TO MSG-COD-SIST
                               MOVE 'FECNAC   NEX' TO MSG-COD-MENS
                               PERFORM GET-MSG
                               MOVE MSG-GLS-DESC  TO FRM-MENS
                               MOVE FRM-SUAR-MAL  TO FRM-SUAR
                           ELSE
                               NEXT SENTENCE
                       ELSE
                           MOVE 'COL'          TO MSG-COD-SIST
                           MOVE 'CLI    NODCP' TO MSG-COD-MENS IN MSG
                           PERFORM GET-MSG
                           MOVE MSG-GLS-DESC  TO FRM-MENS
                           MOVE FRM-SUAR-MAL  TO FRM-SUAR
                   ELSE
                       GO TO FIN-VAL-DBC-NUM-ICLI
               ELSE
      *AFRI-INI/SEP2005
               IF SCR-HDR-MRCA = 'BCS'
                   MOVE 'COL'          TO MSG-COD-SIST
                   MOVE 'DLC    NODBC' TO MSG-COD-MENS IN MSG
                   PERFORM GET-MSG
                   MOVE 'COL'                   TO WSS-MSG-COD-SIST
                   MOVE MSG-COD-MENS IN MSG     TO WSS-MSG-COD-MENS
                   MOVE SPACES                  TO WSS-MSG-COD-FIL1
                   MOVE DBC-NUM-ICLI IN DLC-FLD TO WSS-DBC-NUM-ICLI
                   MOVE '-'                     TO WSS-MSG-COD-FIL2
                   MOVE DBC-VRF-ICLI IN DLC-FLD TO WSS-DBC-VRF-ICLI
                   MOVE SPACES                  TO WSS-MSG-COD-FIL3
                   MOVE MSG-GLS-DESC            TO WSS-MSG-GLS-DESC
                   MOVE MSG-GLS-DATA            TO WSS-MSG-GLS-DATA
                   MOVE WSS-MENS                TO FRM-MENS
                   MOVE FRM-SUAR-MAL            TO FRM-SUAR
               ELSE
      *AFRI-INI/SEP2005
                   MOVE 'COL'          TO MSG-COD-SIST
                   MOVE 'OPC    NODBC' TO MSG-COD-MENS IN MSG
                   PERFORM GET-MSG
                   MOVE MSG-GLS-DESC  TO FRM-MENS
                   MOVE FRM-SUAR-MAL  TO FRM-SUAR.
      * RBG/FIN/17/ABR/1997
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == DBC_NUM_ICLI$1
    == ========================================================================================== -->

  <section name="DBC_NUM_ICLI$1" concatenate="5">

    <code><![CDATA[      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == DBC_VRF_ICLI
    == ========================================================================================== -->

  <section name="DBC_VRF_ICLI">

    <code><![CDATA[      *<<<< DBC_VRF_ICLI
           IF DBC-IND-ICLI IN DLC-FLD = 'M'
      *ISP NO ACEPTA MULTIPLES DEUDORES INDIRECTOS PARA VERSION BCI
               MOVE 'COL' TO TAB-COD-SIST
               MOVE 'VSN' TO TAB-COD-TTAB IN TAB
               MOVE 'BCI    MDIND' TO TAB-COD-CTAB IN TAB
               PERFORM VAL-COD
               IF MSG-COD-MENS NOT > SPACES

                   MOVE ZEROES TO DBC-NUM-ICLI IN DLC-FLD
                   MOVE SPACES TO DBC-VRF-ICLI IN DLC-FLD
                   MOVE SPACES TO DBC-GLS-ICLI IN DLC-FLD
                   MOVE 'COL'          TO MSG-COD-SIST
                   MOVE 'DLC    MDIND' TO MSG-COD-MENS
                   PERFORM GET-MSG
                   MOVE MSG-GLS-DESC TO DBC-GLS-NOMC IN DLC-FLD
                   GO TO FIN-VAL-DBC-VRF-ICLI
               ELSE
                   MOVE 'COL'          TO MSG-COD-SIST
                   MOVE 'BCI    MDIND' TO MSG-COD-MENS
                   PERFORM GET-MSG
                   MOVE MSG-GLS-DESC TO FRM-MENS
                   MOVE FRM-SUAR-MAL TO FRM-SUAR
                   GO TO FIN-VAL-DBC-VRF-ICLI.

      *VAL-RUT Valida Rut
           IF DBC-NUM-ICLI IN DLC-FLD NOT > ZEROES
               MOVE SPACES TO DBC-VRF-ICLI IN DLC-FLD
                              DBC-IND-ICLI IN DLC-FLD
                              DBC-GLS-ICLI IN DLC-FLD
                              RDC-CAI-ICLI IN DLC-FLD
                              RDC-IIC-ICLI IN DLC-FLD
                              GO TO FIN-VAL-DBC-VRF-ICLI.
           MOVE DBC-NUM-ICLI IN DLC-FLD TO IDC-NUM-RUTV.
           MOVE DBC-VRF-ICLI IN DLC-FLD TO IDC-VRF-RUTV.
           PERFORM VAL-RUT.
           IF MSG-COD-MENS = SPACES AND
              DBC-NUM-ICLI IN DLC-FLD > ZEROES
               MOVE DBC-NUM-ICLI IN DLC-FLD TO DBC-NUM-ICLI IN DBC
               MOVE DBC-IND-ICLI IN DLC-FLD TO DBC-IND-ICLI IN DBC
               MOVE DBC-GLS-ICLI IN DLC-FLD TO DBC-GLS-ICLI IN DBC
               MOVE 'DBC-IDC-ICLI'  TO FIO-AKEY
               MOVE FIO-GET-KEY-ALT TO FIO-CMND
               PERFORM SGC-FIO-DBC
               IF NOT FIO-STAT-OKS
                   MOVE 'SGC'        TO MSG-COD-SIST
                   MOVE 'CLI    NEX' TO MSG-COD-MENS
                   PERFORM GET-MSG
                   MOVE MSG-GLS-DESC IN MSG TO DBC-GLS-NOMC IN DLC-FLD
                   MOVE MSG-GLS-DESC TO FRM-MENS
                   MOVE FRM-SUAR-MAL TO FRM-SUAR
               ELSE
                   MOVE DBC-GLS-NOMC IN DBC TO CPT-STRN
                   PERFORM CPT-BLKS
                   MOVE CPT-STRN            TO DBC-GLS-NOMC IN DLC-FLD
                   MOVE DBC-CAI-ICLI IN DBC TO RDC-CAI-ICLI IN DLC-FLD
                   MOVE DBC-IIC-ICLI IN DBC TO RDC-IIC-ICLI IN DLC-FLD
                   MOVE DBC-NUM-ICLI IN DBC TO DBC-NUM-ICLI IN DLC-FLD
                   MOVE DBC-IND-ICLI IN DBC TO DBC-IND-ICLI IN DLC-FLD
                   MOVE DBC-GLS-ICLI IN DBC TO DBC-GLS-ICLI IN DLC-FLD
                   MOVE DBC-VRF-ICLI IN DBC TO DBC-VRF-ICLI IN DLC-FLD
                   MOVE WSS-HAY TO WSS-FRDC.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    ==
    == ========================================================================================== -->

</additional>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/addit/addit_sgc_qtx_bq.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<additional xmlns        = "http://cl/bee/genfrmjava/adddef/schema"
      xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation = "http://cl/bee/genfrmjava/adddef/schema adddef.xsd"
      system             = "SGC"
      form               = "QTX">

  <!-- ========================================================================================== ==
    == FIN_FRM_COD_CPTO
    == ========================================================================================== -->

  <section name="FIN_FRM_COD_CPTO">

    <code><![CDATA[      *<<<<
           IF FRM-COD-CPTO IN QTX-FLD > SPACES
              MOVE 'SGC'                   TO TAB-COD-SIST
              MOVE 'TXO'                   TO TAB-COD-TTAB IN TAB
              MOVE FRM-COD-CPTO IN QTX-FLD TO TAB-COD-CTAB IN TAB
              PERFORM VAL-COD.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == FIN_FRM_FEC_FFIH
    == ========================================================================================== -->

  <section name="FIN_FRM_FEC_FFIH">

    <code><![CDATA[      *<<<<FIN_FRM_FEC_FFIH
           MOVE FRM-NUM-SFID IN QTX-FLD TO WSS-NUM-SFID IN WSS-VARI.
           MOVE FRM-NUM-AFID IN QTX-FLD TO WSS-NUM-AFID IN WSS-VARI.
           MOVE FRM-NUM-MFID IN QTX-FLD TO WSS-NUM-MFID IN WSS-VARI.
           MOVE FRM-NUM-DFID IN QTX-FLD TO WSS-NUM-DFID IN WSS-VARI.

           MOVE FRM-NUM-SFIH IN QTX-FLD TO WSS-NUM-SFIH IN WSS-VARI.
           MOVE FRM-NUM-AFIH IN QTX-FLD TO WSS-NUM-AFIH IN WSS-VARI.
           MOVE FRM-NUM-MFIH IN QTX-FLD TO WSS-NUM-MFIH IN WSS-VARI.
           MOVE FRM-NUM-DFIH IN QTX-FLD TO WSS-NUM-DFIH IN WSS-VARI.
           IF (WSS-FEC-FFID IN WSS-VARI > ZEROES AND
               WSS-FEC-FFIH IN WSS-VARI > ZEROES AND
               WSS-FEC-FFIH IN WSS-VARI NOT > WSS-FEC-FFID IN WSS-VARI)
               MOVE 'SGC'        TO MSG-COD-SIST
               MOVE 'FFIH<FFID'  TO MSG-COD-MENS
               PERFORM GET-MSG
               MOVE MSG-GLS-DESC TO FRM-MENS
               MOVE FRM-SUAR-MAL TO FRM-SUAR
               GO TO FIN-VAL-FRM-FEC-FFIH.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == FIN_FRM_FEC_FINH
    == ========================================================================================== -->

  <section name="FIN_FRM_FEC_FINH">

    <code><![CDATA[      *<<<<
           MOVE FRM-NUM-SIND IN QTX-FLD TO WSS-NUM-SIND IN WSS-VARI.
           MOVE FRM-NUM-AIND IN QTX-FLD TO WSS-NUM-AIND IN WSS-VARI.
           MOVE FRM-NUM-MIND IN QTX-FLD TO WSS-NUM-MIND IN WSS-VARI.
           MOVE FRM-NUM-DIND IN QTX-FLD TO WSS-NUM-DIND IN WSS-VARI.

           MOVE FRM-NUM-SINH IN QTX-FLD TO WSS-NUM-SINH IN WSS-VARI.
           MOVE FRM-NUM-AINH IN QTX-FLD TO WSS-NUM-AINH IN WSS-VARI.
           MOVE FRM-NUM-MINH IN QTX-FLD TO WSS-NUM-MINH IN WSS-VARI.
           MOVE FRM-NUM-DINH IN QTX-FLD TO WSS-NUM-DINH IN WSS-VARI.

           IF (WSS-FEC-FIND IN WSS-VARI > ZEROES AND
               WSS-FEC-FINH IN WSS-VARI > ZEROES AND
               WSS-FEC-FINH IN WSS-VARI NOT > WSS-FEC-FIND IN WSS-VARI)
               MOVE 'SGC'        TO MSG-COD-SIST
               MOVE 'FINH<FIND'  TO MSG-COD-MENS
               PERFORM GET-MSG
               MOVE MSG-GLS-DESC TO FRM-MENS
               MOVE FRM-SUAR-MAL TO FRM-SUAR
               GO TO FIN-VAL-FRM-FEC-FINH.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == FIN_FRM_MSC_STAT
    == ========================================================================================== -->

  <section name="FIN_FRM_MSC_STAT">

    <code><![CDATA[      *<<<<
           IF FRM-MSC-STAT IN QTX-FLD > SPACES
              MOVE 'GNS'                   TO TAB-COD-SIST
              MOVE 'SON'                   TO TAB-COD-TTAB IN TAB
              MOVE FRM-MSC-STAT IN QTX-FLD TO TAB-COD-CTAB IN TAB
              PERFORM VAL-COD.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == INI_FRM_FEC_FFID
    == ========================================================================================== -->

  <section name="INI_FRM_FEC_FFID">

    <code><![CDATA[MAN        MOVE FEC-CHOY-N TO FEC-CHOY.
MAN        MOVE FEC-VHBL-N TO FEC-VHBL.
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == INI_FRM_FEC_FFIH
    == ========================================================================================== -->

  <section name="INI_FRM_FEC_FFIH">

    <code><![CDATA[MAN        MOVE FEC-CHOY-N TO FEC-CHOY.
MAN        MOVE FEC-VHBL-N TO FEC-VHBL.
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == INI_FRM_FEC_FIND
    == ========================================================================================== -->

  <section name="INI_FRM_FEC_FIND">

    <code><![CDATA[MAN        MOVE FEC-CHOY-N TO FEC-CHOY.
MAN        MOVE FEC-VHBL-N TO FEC-VHBL.
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == INI_FRM_FEC_FINH
    == ========================================================================================== -->

  <section name="INI_FRM_FEC_FINH">

    <code><![CDATA[MAN        MOVE FEC-CHOY-N TO FEC-CHOY.
MAN        MOVE FEC-VHBL-N TO FEC-VHBL.
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == INI_NUM_FLD_QTX
    == ========================================================================================== -->

  <section name="INI_NUM_FLD_QTX">

    <code><![CDATA[     *<<<<INI_EDT_FLD_QTX
           IF FRM-NUM-ITXO-LEN IN QTX-FLD(1) = FRM-ERR-NUME
                MOVE FRM-IND-ERRO TO FRM-NUM-ITXO-LEN IN QTX-FLD(1)
                GO TO FIN-EDT-FLD-QTX.
           MOVE FRM-NUM-ITXO IN QTX-FLD(1) TO
                FRM-NUM-ITXO-EDT IN QTX-EDT.
           MOVE FRM-NUM-ITXO-EDT IN QTX-EDT TO
                FRM-NUM-ITXO-ALF IN QTX-FLD(1).
           IF FRM-NUM-ITXO-LEN IN QTX-FLD(2) = FRM-ERR-NUME
                MOVE FRM-IND-ERRO TO FRM-NUM-ITXO-LEN IN QTX-FLD(2)
                GO TO FIN-EDT-FLD-QTX.
           MOVE FRM-NUM-ITXO IN QTX-FLD(2) TO
                FRM-NUM-ITXO-EDT IN QTX-EDT.
           MOVE FRM-NUM-ITXO-EDT IN QTX-EDT TO
                FRM-NUM-ITXO-ALF IN QTX-FLD(2).
           IF FRM-NUM-ITXO-LEN IN QTX-FLD(3) = FRM-ERR-NUME
                MOVE FRM-IND-ERRO TO FRM-NUM-ITXO-LEN IN QTX-FLD(3)
                GO TO FIN-EDT-FLD-QTX.
           MOVE FRM-NUM-ITXO IN QTX-FLD(3) TO
                FRM-NUM-ITXO-EDT IN QTX-EDT.
           MOVE FRM-NUM-ITXO-EDT IN QTX-EDT TO
                FRM-NUM-ITXO-ALF IN QTX-FLD(3).
           IF FRM-NUM-ITXO-LEN IN QTX-FLD(4) = FRM-ERR-NUME
                MOVE FRM-IND-ERRO TO FRM-NUM-ITXO-LEN IN QTX-FLD(4)
                GO TO FIN-EDT-FLD-QTX.
           MOVE FRM-NUM-ITXO IN QTX-FLD(4) TO
                FRM-NUM-ITXO-EDT IN QTX-EDT.
           MOVE FRM-NUM-ITXO-EDT IN QTX-EDT TO
                FRM-NUM-ITXO-ALF IN QTX-FLD(4).
           IF FRM-NUM-ITXO-LEN IN QTX-FLD(5) = FRM-ERR-NUME
                MOVE FRM-IND-ERRO TO FRM-NUM-ITXO-LEN IN QTX-FLD(5)
                GO TO FIN-EDT-FLD-QTX.
           MOVE FRM-NUM-ITXO IN QTX-FLD(5) TO
                FRM-NUM-ITXO-EDT IN QTX-EDT.
           MOVE FRM-NUM-ITXO-EDT IN QTX-EDT TO
                FRM-NUM-ITXO-ALF IN QTX-FLD(5).
]]></code>

  </section>

  <!-- ========================================================================================== ==
    ==
    == ========================================================================================== -->

</additional>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/addit/addit_sgc_ipc_bu.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<additional xmlns        = "http://cl/bee/genfrmjava/adddef/schema"
      xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation = "http://cl/bee/genfrmjava/adddef/schema adddef.xsd"
      system             = "SGC"
      form               = "IPC">

  <!-- ========================================================================================== ==
    == FIN_IPC_COD_TDOC
    == ========================================================================================== -->

  <section name="FIN_IPC_COD_TDOC">

    <code><![CDATA[      *<<<< FIN_VAL_IPC_COD_TDOC
           MOVE 'SGC' TO TAB-COD-SIST.
           MOVE 'TFO' TO TAB-COD-TTAB IN TAB.
           MOVE IPC-COD-TDOC IN IPC-FLD TO TAB-COD-CTAB IN TAB.
           PERFORM VAL-COD.
           IF MSG-COD-MENS NOT = SPACES
              MOVE 'SGC'        TO MSG-COD-SIST
              MOVE 'COD    EXI  ' TO MSG-COD-MENS
              PERFORM GET-MSG
              MOVE MSG-GLS-DESC TO FRM-MENS
              MOVE FRM-SUAR-MAL TO FRM-SUAR.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == FIN_PUT_DBC_IPC
    == ========================================================================================== -->

  <section name="FIN_PUT_DBC_IPC">

    <code><![CDATA[      *<<<< FIN_PUT_DBC_IPC
           MOVE DBC-GLS-NOMC IN DBC TO CPT-STRN.
           PERFORM CPT-BLKS.
           MOVE CPT-STRN            TO DBC-GLS-NOMC IN IPC-FLD.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == FIN_PUT_RPR_IPC
    == ========================================================================================== -->

  <section name="FIN_PUT_RPR_IPC">

    <code><![CDATA[      *BUS-TAB busca glosa de codigo en tabla
           IF RPR-IND-ESTA IN IPC-FLD > SPACES
               MOVE 'SGC' TO TAB-COD-SIST
               MOVE 'EST ' TO TAB-COD-TTAB IN TAB
               MOVE RPR-IND-ESTA IN IPC-FLD TO TAB-COD-CTAB IN TAB
               PERFORM BUS-TAB
               MOVE TAB-GLS-DESC IN TAB TO
                    FRM-GLS-ESTA IN IPC-FLD
           ELSE
               MOVE SPACES TO FRM-GLS-ESTA IN IPC-FLD.
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == FIN_VAL_CON_KEY_IPC
    == ========================================================================================== -->

  <section name="FIN_VAL_CON_KEY_IPC">

    <code><![CDATA[      *<<<< FIN_VAL_CON_KEY_IPC
           IF     DBC-NUM-ICLI IN IPC-FLD NOT > ZEROES
              AND IPC-IIC-IFOL IN IPC-FLD NOT > SPACES
                PERFORM ERR-KEY
                PERFORM FST-KEY-IPC.

            IF    IPC-COD-TDOC IN IPC-FLD NOT > SPACES
                PERFORM ERR-KEY
                MOVE 'S' TO FRM-UCUR
                MOVE -1 TO IPC-COD-TDOC-LEN IN IPC-FLD
                MOVE FRM-POS-CURS TO IPC-COD-TDOC-LEN IN IPC-FLD.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    == INI_FST_KEY_IPC
    == ========================================================================================== -->

  <section name="INI_FST_KEY_IPC">

    <code><![CDATA[      *<<<< INI_FST_KEY_IPC
           MOVE -1 TO DBC-NUM-ICLI-LEN IN IPC-FLD.
      *>>>>
]]></code>

  </section>

  <!-- ========================================================================================== ==
    ==
    == ========================================================================================== -->

</additional>
