=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/build/schemaorg_apache_xmlbeans/src/domaindef.xsd
<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema'
           targetNamespace='http://cl/bee/genfrmjava/domaindef/schema'
                     xmlns='http://cl/bee/genfrmjava/domaindef/schema'>

 <!-- ========================================================================================== ==
   == domains
   == ========================================================================================== -->

 <xsd:element name='domains'>

  <xsd:complexType>

   <xsd:sequence>
     <xsd:element ref='domain' minOccurs='0' maxOccurs='unbounded'/>
   </xsd:sequence>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == domain
   == ========================================================================================== -->

 <xsd:element name='domain'>

  <xsd:complexType>

    <xsd:attribute name='name'       type='xsd:string' use='required'/>
    <xsd:attribute name='system'     type='xsd:string' use='required'/>
    <xsd:attribute name='registry'   type='xsd:string' default=''/>
    <xsd:attribute name='table'      type='xsd:string' use='required'/>
    <xsd:attribute name='validation' type='xsd:string' default=''/>
    <xsd:attribute name='search'     type='xsd:string' default=''/>

  </xsd:complexType>

 </xsd:element>

</xsd:schema>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/domain-range/domain_dap.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<domains xmlns              = "http://cl/bee/genfrmjava/domaindef/schema"
         xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation = "http://cl/bee/genfrmjava/domaindef/schema domaindef.xsd">

  <domain name="CODACT" system="TAB" registry="TAB" table="ACT " validation="VALCOD" search="BUSTAB" />
  <domain name="CODAGES" system="TAB" registry="TAB" table="ADG " />
  <domain name="CODBNCA" system="TAB" registry="USR" table="BAC " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCBCO" system="TAB" registry="PZA" table="BCO " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCNEG" system="TAB" registry="USR" table="GCN " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCNL" system="TAB" registry="TAB" table="CNL " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCOMU" system="TAB" table="COM " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCOOC" system="COL" registry="TAB" table="AUX " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCOPD" system="DAP" registry="TAB" table="AUX " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCTAB" system="TAB" table="SVC " validation="VALCOD" />
  <domain name="CODCUSR" system="TAB" table="CUS " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCUST" system="DAP" registry="OPD" table="CUS " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCYA" system="TAB" registry="MSC" table="TCYA" validation="VALIND" search="BUSMSC" />
  <domain name="CODDBHB" system="TAB" registry="TAB" table="IDH " validation="VALCOD" search="BUSTAB" />
  <domain name="CODDEVL" system="GNS" registry="TAB" table="SON " validation="VALCOD" search="BUSTAB" />
  <domain name="CODDPTO" system="TAB" registry="COM" table="DPT " validation="VALCOD" search="BUSTAB" />
  <domain name="CODEJEC" system="TAB" registry="USR" table="USR " validation="VALUSR" search="BUSUSR" />
  <domain name="CODGARA" system="DAP" registry="OPD" table="GAR " validation="VALCOD" search="BUSTAB" />
  <domain name="CODIEPD" system="DAP" registry="TAB" table="CEP " validation="VALCOD" search="BUSTAB" />
  <domain name="CODMORE" system="DAP" registry="DAP" table="MDR " validation="VALCOD" search="BUSTAB" />
  <domain name="CODMVTO" system="DAP" registry="TAB" table="MVT " validation="VALCOD" search="BUSTAB" />
  <domain name="CODOFIC" system="TAB" registry="OFI" table="OFI " validation="VALOFI" search="BUSOFI" />
  <domain name="CODPAIS" system="TAB" registry="COM" table="PAI " validation="VALCOD" search="BUSTAB" />
  <domain name="CODPLAT" system="TAB" registry="USR" table="PLT " validation="VALCOD" search="BUSTAB" />
  <domain name="CODPLZA" system="TAB" registry="OFI" table="PZA " validation="VALCOD" search="BUSTAB" />
  <domain name="CODPLZO" system="TAB" registry="TAB" table="PZO " validation="VALCOD" search="BUSTAB" />
  <domain name="CODPRVC" system="TAB" registry="COM" table="PRV " validation="VALCOD" search="BUSTAB" />
  <domain name="CODPTR" system="TAB" registry="TAB" table="PTR " validation="VALCOD" search="BUSTAB" />
  <domain name="CODREGI" system="TAB" registry="COM" table="REG " validation="VALCOD" search="BUSTAB" />
  <domain name="CODREGL" system="TAB" registry="USR" table="RGN " validation="VALCOD" search="BUSTAB" />
  <domain name="CODSEPD" system="DAP" registry="TAB" table="SEP " validation="VALCOD" search="BUSTAB" />
  <domain name="CODSTT" system="GNS" registry="TAB" table="STT " validation="VALCOD" search="BUSTAB" />
  <domain name="CODTALG" system="DAP" registry="TAB" table="ALG " validation="VALCOD" search="BUSTAB" />
  <domain name="CODTCCT" system="TAB" registry="TAB" table="TCC " validation="VALCOD" search="BUSTAB" />
  <domain name="CODTDU" system="TAB" registry="USR" table="EJC " validation="VALTDU" search="BUSUSR" />
  <domain name="CODTEJE" system="TAB" registry="USR" table="CEP " />
  <domain name="CODTOPD" system="TAB" registry="TAB" table="TIO " validation="VALCOD" search="BUSTAB" />
  <domain name="CODTTA1" system="TAB" table="IVB " validation="VALCOD" search="BUSTAB" />
  <domain name="CODTTAB" system="TAB" table="USR " validation="VALCOD" search="BUSTAB" />
  <domain name="CODUBIC" system="TAB" table="UBI " validation="VALCOD" search="BUSTAB" />
  <domain name="CODVCAM" system="TAB" registry="TAB" table="VLR " validation="VALCOD" search="BUSTAB" />
  <domain name="CODVCOC" system="TAB" registry="TAB" table="VLR " validation="VALCOD" search="BUSTAB" />
  <domain name="CODVIGE" system="GNS" registry="TAB" table="SON " validation="VALCOD" search="BUSTAB" />
  <domain name="INDACPA" system="TAB" registry="MSC" table="ACPA" validation="VALIND" search="BUSMSC" />
  <domain name="INDDURV" system="TAB" registry="MSC" table="IPER" validation="VALIND" search="BUSMSC" />
  <domain name="INDLOGA" system="GNS" registry="TAB" table="SON " validation="VALCOD" search="BUSTAB" />
  <domain name="INDRETD" system="TAB" registry="MSC" table="IPER" validation="VALIND" search="BUSMSC" />
  <domain name="INDSEVE" system="TAB" registry="MSC" table="IPER" validation="VALIND" search="BUSMSC" />
  <domain name="INDTCAD" system="TAB" registry="MSC" table="TCYA" />
  <domain name="INDTCOL" system="COL" registry="MSC" table="TCOL" validation="VALIND" search="BUSMSC" />
  <domain name="INDVIGE" system="GNS" registry="TAB" table="SON " validation="VALCOD" search="BUSTAB" />
  <domain name="TABCAP" system="TAB" table="CAP " validation="VALCOD" search="BUSTAB" />
  <domain name="TABFOR" system="TAB" table="FOR " validation="VALCOD" search="BUSTAB" />
</domains>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/domain-range/domain_gns.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<domains xmlns              = "http://cl/bee/genfrmjava/domaindef/schema"
         xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation = "http://cl/bee/genfrmjava/domaindef/schema domaindef.xsd">

  <domain name="CODACCI" system="GNS" table="AOC " validation="VALCOD" search="BUSTAB" />
  <domain name="CODAMPA" system="GNS" registry="TAB" table="AMP " validation="VALCOD" search="BUSTAB" />
  <domain name="CODASCR" system="GNS" registry="TAB" table="ASC " validation="VALCOD" search="BUSTAB" />
  <domain name="CODBANC" system="TAB" table="BCO " />
  <domain name="CODBNCO" system="GNS" table="BCO " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCAMB" system="GNS" table="BDC " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCART" system="GNS" table="CRT " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCDGO" system="GNS" registry="REG" table="222 " />
  <domain name="CODCFNC" system="GNS" table="FDC " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCMND" system="GNS" table="CMN " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCNAL" system="GNS" table="CNL " />
  <domain name="CODCONS" system="GNS" table="SON " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCVDT" system="GNS" table="VDT " validation="VALCOD" search="BUSTAB" />
  <domain name="CODFST1" system="GNS" table="TDP " validation="VALCOD" search="BUSTAB" />
  <domain name="CODGRPO" system="GNS" table="GRP " validation="VALCOD" search="BUSTAB" />
  <domain name="CODINST" system="GNS" registry="TAB" table="IST " validation="VALCOD" search="BUSTAB" />
  <domain name="CODLCLX" system="GNS" registry="TAB" table="CLX " validation="VALCOD" search="BUSTAB" />
  <domain name="CODLGMG" system="GNS" registry="TAB" table="LMG " validation="VALCOD" search="BUSTAB" />
  <domain name="CODLGMM" system="GNS" registry="TAB" table="LMM " validation="VALCOD" search="BUSTAB" />
  <domain name="CODLGMV" system="GNS" registry="TAB" table="LMV " validation="VALCOD" search="BUSTAB" />
  <domain name="CODLSLX" system="GNS" registry="TAB" table="SLX " validation="VALCOD" search="BUSTAB" />
  <domain name="CODMODO" system="GNS" registry="TAB" table="MDO " validation="VALCOD" search="BUSTAB" />
  <domain name="CODMRCA" system="GNS" table="MRC " validation="VALCOD" search="BUSTAB" />
  <domain name="CODMSAL" system="GNS" registry="TAB" table="MSL " validation="VALCOD" />
  <domain name="CODOFIA" system="TAB" table="OFI " />
  <domain name="CODOFIC" system="TAB" registry="OFI" table="OFI " />
  <domain name="CODPAMB" system="GNS" table="BDC " validation="VALCOD" search="BUSTAB" />
  <domain name="CODPENT" system="GNS" table="EDC " validation="VALCOD" search="BUSTAB" />
  <domain name="CODPFNC" system="GNS" table="FDC " validation="VALCOD" search="BUSTAB" />
  <domain name="CODPMOD" system="GNS" table="MDC " validation="VALCOD" search="BUSTAB" />
  <domain name="CODPRUE" system="STM" table="TBL " />
  <domain name="CODPUSR" system="GNS" table="UDC " validation="VALCOD" search="BUSTAB" />
  <domain name="CODPVDT" system="GNS" table="VDT " validation="VALCOD" search="BUSTAB" />
  <domain name="CODSIST" system="GNS" table="SIS " validation="VALCOD" search="BUSTAB" />
  <domain name="CODSSDS" system="GNS" table="SDS " />
  <domain name="CODTCTL" system="GNS" registry="TAB" table="TCT " />
  <domain name="CODTDPU" system="GNS" table="TDP " validation="VALCOD" search="BUSTAB" />
  <domain name="CODTENT" system="GNS" registry="TAB" table="TEN " validation="VALCOD" search="BUSTAB" />
  <domain name="CODTFUN" system="GNS" registry="TAB" table="TFN " validation="VALCOD" search="BUSTAB" />
  <domain name="CODTINF" system="GNS" registry="TAB" table="TIN " />
  <domain name="CODUCVT" system="GNS" table="UDC " validation="VALCOD" search="BUSTAB" />
  <domain name="CODUIDD" system="GNS" table="UIM " validation="VALCOD" />
  <domain name="CODUSER" system="TAB" table="USR " validation="VALUSR" search="BUSUSR" />
  <domain name="CODUSUA" system="TAB" table="USR " validation="VALUSR" search="BUSUSR" />
  <domain name="CODVIGE" system="GNS" table="SON " validation="VALCOD" search="BUSTAB" />
  <domain name="CUDUSER" system="TAB" registry="USR" table="USR " validation="VALUSER" search="BUSUSR" />
  <domain name="GLSMODO" system="GNS" registry="TAB" table="MRL " validation="VALCOD" search="BUSTAB" />
  <domain name="GLSTPRO" system="GNS" registry="TAB" table="TPR " validation="VALCOD" search="BUSTAB" />
  <domain name="GNSMUL" system="   " table="    " validation="PARRAFO-VAL" search="PARRAFO-BUSQ" />
  <domain name="IDDGRPO" system="GNS" registry="TAB" table="GID " />
  <domain name="IDDTENT" system="GNS" registry="TAB" table="TID " />
  <domain name="INDECIC" system="SGC" table="SEXO" />
  <domain name="INDECIV" system="SGC" table="ECIV" />
  <domain name="INDINDI" system="GNS" table="111 " validation="VALCOD" search="NO" />
  <domain name="INDIPRV" system="GNS" registry="TAB" table="IPV " validation="VALCOD" search="BUSTAB" />
  <domain name="INDRESP" system="GNS" table="SON " validation="VALCOD" search="BUSTAB" />
  <domain name="INDSINO" system="GNS" registry="TAB" table="SON " validation="VALCOD" search="BUSTAB" />
  <domain name="INDVIGE" system="GNS" table="SON " />
  <domain name="ITKCRESP" system="GNS" table="SRT " validation="VALCOD" search="BUSTAB" />
  <domain name="ITKIRESP" system="GNS" table="IRT " validation="VALCOD" search="BUSTAB" />
  <domain name="MSCMSCL" system="GNS" table="333 " />
  <domain name="MSCSEXC" system="SGC" table="SEXO" />
  <domain name="MSCSEXO" system="SGC" registry="XXX" table="SEXO" />
  <domain name="MSCSTAT" system="GNS" table="SON " validation="VALCOD" search="BUSTAB" />
  <domain name="MSCVIGE" system="GNS" registry="MSC" table="VIGE" />
  <domain name="PANCLRP" system="GNS" registry="TAB" table="ILP " />
  <domain name="PANCLRV" system="GNS" registry="TAB" table="ILV " />
  <domain name="PANTCLA" system="GNS" registry="TAB" table="TCP " />
  <domain name="PANTFUN" system="GNS" registry="TAB" table="TFP " />
  <domain name="PCKSTAT" system="GNS" table="SPK " validation="VALCOD" search="BUSTAB" />
  <domain name="RF1CMND" system="GNS" registry="RF1" table="RFP " validation="VALCOD" search="BUSTAB" />
  <domain name="XXXCDGO" system="GNS" table="444 " />
</domains>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/domain-range/domain_tab.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<domains xmlns              = "http://cl/bee/genfrmjava/domaindef/schema"
         xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation = "http://cl/bee/genfrmjava/domaindef/schema domaindef.xsd">

  <domain name="CODACT" system="TAB" registry="TAB" table="ACT " validation="VALCOD" search="BUSTAB" />
  <domain name="CODAGES" system="TAB" registry="TAB" table="ADG " />
  <domain name="CODBNCA" system="TAB" registry="USR" table="BAC " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCBCO" system="TAB" registry="PZA" table="BCO " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCNEG" system="TAB" registry="USR" table="GCN " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCNL" system="TAB" registry="TAB" table="CNL " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCOMU" system="TAB" table="COM " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCOOC" system="COL" registry="TAB" table="AUX " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCTAB" system="TAB" table="SVC " validation="VALCOD" />
  <domain name="CODCUSR" system="TAB" table="CUS " validation="VALCOD" search="BUSTAB" />
  <domain name="CODCYA" system="TAB" registry="MSC" table="TCYA" validation="VALIND" search="BUSMSC" />
  <domain name="CODDPTO" system="TAB" registry="COM" table="DPT " validation="VALCOD" search="BUSTAB" />
  <domain name="CODOFIC" system="TAB" registry="OFI" table="OFI " validation="VALOFI" search="BUSOFI" />
  <domain name="CODPAIS" system="TAB" registry="COM" table="PAI " validation="VALCOD" search="BUSTAB" />
  <domain name="CODPLAT" system="TAB" registry="USR" table="PLT " validation="VALCOD" search="BUSTAB" />
  <domain name="CODPLZA" system="TAB" registry="OFI" table="PZA " validation="VALCOD" search="BUSTAB" />
  <domain name="CODPRVC" system="TAB" registry="COM" table="PRV " validation="VALCOD" search="BUSTAB" />
  <domain name="CODPTR" system="TAB" registry="TAB" table="PTR " validation="VALCOD" search="BUSTAB" />
  <domain name="CODREGI" system="TAB" registry="COM" table="REG " validation="VALCOD" search="BUSTAB" />
  <domain name="CODREGL" system="TAB" registry="USR" table="RGN " validation="VALCOD" search="BUSTAB" />
  <domain name="CODSTT" system="GNS" registry="TAB" table="STT " validation="VALCOD" search="BUSTAB" />
  <domain name="CODTDU" system="TAB" registry="USR" table="EJC " validation="VALTDU" search="BUSUSR" />
  <domain name="CODTEJE" system="TAB" registry="USR" table="CEP " />
  <domain name="CODTTA1" system="TAB" table="IVB " validation="VALCOD" search="BUSTAB" />
  <domain name="CODTTAB" system="TAB" table="USR " validation="VALCOD" search="BUSTAB" />
  <domain name="CODUBIC" system="TAB" table="UBI " validation="VALCOD" search="BUSTAB" />
  <domain name="CODVCOC" system="TAB" registry="TAB" table="VLR " validation="VALCOD" search="BUSTAB" />
  <domain name="INDACPA" system="TAB" registry="MSC" table="ACPA" validation="VALIND" search="BUSMSC" />
  <domain name="INDLOGA" system="GNS" registry="TAB" table="SON " validation="VALCOD" search="BUSTAB" />
  <domain name="INDTCOL" system="COL" registry="MSC" table="TCOL" validation="VALIND" search="BUSMSC" />
  <domain name="INDVIGE" system="GNS" registry="TAB" table="SON " validation="VALCOD" search="BUSTAB" />
  <domain name="TABCAP" system="TAB" table="CAP " validation="VALCOD" search="BUSTAB" />
  <domain name="TABFOR" system="TAB" table="FOR " validation="VALCOD" search="BUSTAB" />
</domains>
