=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/build/schemaorg_apache_xmlbeans/src/formdef.xsd
<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema'
           targetNamespace='http://cl/bee/genfrmjava/formdef/schema'
                     xmlns='http://cl/bee/genfrmjava/formdef/schema'>

 <!-- ========================================================================================== ==
   == form
   == ========================================================================================== -->

 <xsd:element name='form'>

  <xsd:complexType>

   <xsd:sequence minOccurs='1' maxOccurs='unbounded'>
    <xsd:choice>
      <xsd:element ref='field'/>
      <xsd:element ref='array'/>
      <xsd:element ref='primary'/>
      <xsd:element ref='foreign'/>
      <xsd:element ref='text'/>
    </xsd:choice>
   </xsd:sequence>

   <xsd:attribute name='entity' type='xsd:string' use='required'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == field
   == ========================================================================================== -->

 <xsd:element name='field'>

  <xsd:complexType>

   <xsd:sequence minOccurs='0' maxOccurs='unbounded'>
    <xsd:choice>
      <xsd:element ref='type'/>
      <xsd:element ref='fms'/>
      <xsd:element ref='default'/>
      <xsd:element ref='index'/>
    </xsd:choice>
   </xsd:sequence>

   <xsd:attribute name='name'    type='xsd:string' use='required'/>
   <xsd:attribute name='special' type='xsd:string' default=''/>
  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == array
   == ========================================================================================== -->

 <xsd:element name='array'>

  <xsd:complexType>

   <xsd:sequence>
    <xsd:element ref='field' maxOccurs='unbounded'/>
   </xsd:sequence>

   <xsd:attribute name='size' type='xsd:unsignedInt' use='required'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == primary
   == ========================================================================================== -->

 <xsd:element name='primary'>

  <xsd:complexType>

   <xsd:sequence>
    <xsd:element ref='field' maxOccurs='unbounded'/>
   </xsd:sequence>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == foreign
   == ========================================================================================== -->

 <xsd:element name='foreign'>

  <xsd:complexType>

   <xsd:sequence>
    <xsd:element ref='field' maxOccurs='unbounded'/>
   </xsd:sequence>

   <xsd:attribute name='entity' type='xsd:string' use='required'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == text
   == ========================================================================================== -->

 <xsd:element name='text'>

  <xsd:complexType>

   <xsd:attribute name='caption' type='xsd:string'      use='required'/>
   <xsd:attribute name='row'     type='xsd:unsignedInt' use='required'/>
   <xsd:attribute name='column'  type='xsd:unsignedInt' use='required'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == type
   == ========================================================================================== -->

 <xsd:element name='type'>

  <xsd:complexType>

   <xsd:attribute name='name'     type='TipoType'        use='required'/>
   <xsd:attribute name='size'     type='xsd:unsignedInt' use='required'/>
   <xsd:attribute name='integers' type='xsd:unsignedInt' default='0'/>
   <xsd:attribute name='decimals' type='xsd:unsignedInt' default='0'/>
   <xsd:attribute name='sign'     type='YesNoType'       default='no'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == TipoType
   == ========================================================================================== -->

 <xsd:simpleType name='TipoType'>

  <xsd:restriction base='xsd:string'>
   <xsd:enumeration value='integer'/>
   <xsd:enumeration value='long'   />
   <xsd:enumeration value='double' />
   <xsd:enumeration value='char'   />
   <xsd:enumeration value='boolean'/>
   <xsd:enumeration value='string' />
   <xsd:enumeration value='date'   />
  </xsd:restriction>

 </xsd:simpleType>

 <!-- ========================================================================================== ==
   == YesNoType
   == ========================================================================================== -->

 <xsd:simpleType name='YesNoType'>

  <xsd:restriction base='xsd:string'>
   <xsd:enumeration value='yes'/>
   <xsd:enumeration value='no' />
  </xsd:restriction>

 </xsd:simpleType>

 <!-- ========================================================================================== ==
   == fms
   == ========================================================================================== -->

 <xsd:element name='fms'>

  <xsd:complexType>

   <xsd:attribute name='name'       type='xsd:string'      use='required'/>
   <xsd:attribute name='modifier'   type='ModifierType'    use='required'/>
   <xsd:attribute name='row'        type='xsd:unsignedInt' default='0'/>
   <xsd:attribute name='column'     type='xsd:unsignedInt' default='0'/>
   <xsd:attribute name='picture'    type='xsd:string'      use='required'/>
   <xsd:attribute name='attributes' type='xsd:unsignedInt' use='required'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == ModifierType
   == ========================================================================================== -->

 <xsd:simpleType name='ModifierType'>

  <xsd:restriction base='xsd:string'>
   <xsd:enumeration value='IKY'/>
   <xsd:enumeration value='MKY'/>
   <xsd:enumeration value='AKY'/>
   <xsd:enumeration value='FLD'/>
  </xsd:restriction>

 </xsd:simpleType>

 <!-- ========================================================================================== ==
   == default
   == ========================================================================================== -->

 <xsd:element name='default'>

  <xsd:complexType>

   <xsd:attribute name='value' type='xsd:string'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == index
   == ========================================================================================== -->

 <xsd:element name='index'>

  <xsd:complexType>

   <xsd:sequence>
    <xsd:element ref='pos' maxOccurs='unbounded'/>
   </xsd:sequence>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == pos
   == ========================================================================================== -->

 <xsd:element name='pos'>

  <xsd:complexType>

   <xsd:attribute name='row'    type='xsd:unsignedInt'/>
   <xsd:attribute name='column' type='xsd:unsignedInt'/>

  </xsd:complexType>

 </xsd:element>


</xsd:schema>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/form/form_tab_ofi.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<form xmlns              = "http://cl/bee/genfrmjava/formdef/schema"
      xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation = "http://cl/bee/genfrmjava/formdef/schema formdef.xsd"
      entity             = "TAB_OFI">

  <field name="OFI-COD-OFIC">
    <type name="string" size="3"/>
    <fms name="OFI_IKY_COD_OFIC" modifier="IKY" row="3" column="18" picture="XXX" attributes="2356725"/>
  </field>

  <field name="OFI-CIC-OFIC">
    <type name="string" size="3"/>
    <fms name="OFI_CIC_OFIC" modifier="FLD" row="3" column="53" picture="XXX" attributes="4242933"/>
  </field>

  <field name="OFI-EXT-CTAB">
    <type name="string" size="5"/>
    <fms name="OFI_EXT_CTAB" modifier="FLD" row="3" column="74" picture="XXXXX" attributes="4242933"/>
  </field>

  <field name="OFI-GLS-DESC">
    <type name="string" size="38"/>
    <fms name="OFI_GLS_DESC" modifier="FLD" row="5" column="18" picture="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="4308469"/>
  </field>

  <field name="OFI-GLS-ABRV">
    <type name="string" size="5"/>
    <fms name="OFI_GLS_ABRV" modifier="FLD" row="5" column="74" picture="XXXXX" attributes="4308469"/>
  </field>

  <field name="OFI-GLS-DIRE">
    <type name="string" size="38"/>
    <fms name="OFI_GLS_DIRE" modifier="FLD" row="7" column="18" picture="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="4308469"/>
  </field>

  <field name="OFI-COD-COMU">
    <type name="string" size="4"/>
    <fms name="OFI_COD_COMU" modifier="FLD" row="7" column="75" picture="XXXX" attributes="4242933"/>
  </field>

  <field name="FRM-GLS-COMU">
    <type name="string" size="16"/>
    <fms name="FRM_GLS_COMU" modifier="FLD" row="8" column="63" picture="XXXXXXXXXXXXXXXX" attributes="2161911"/>
  </field>

  <field name="OFI-GLS-TLEX">
    <type name="string" size="38"/>
    <fms name="OFI_GLS_TLEX" modifier="FLD" row="9" column="18" picture="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="4242933"/>
  </field>

  <field name="OFI-COD-PLZA">
    <type name="string" size="4"/>
    <fms name="OFI_COD_PLZA" modifier="FLD" row="9" column="75" picture="XXXX" attributes="4242933"/>
  </field>

  <field name="FRM-GLS-PLZA">
    <type name="string" size="16"/>
    <fms name="FRM_GLS_PLZA" modifier="FLD" row="10" column="63" picture="XXXXXXXXXXXXXXXX" attributes="2161911"/>
  </field>

  <field name="OFI-GLS-FON1">
    <type name="string" size="10"/>
    <fms name="OFI_GLS_FON1" modifier="FLD" row="11" column="18" picture="XXXXXXXXXX" attributes="4242933"/>
  </field>

  <field name="OFI-GLS-FON2">
    <type name="string" size="10"/>
    <fms name="OFI_GLS_FON2" modifier="FLD" row="11" column="33" picture="XXXXXXXXXX" attributes="4505061"/>
  </field>

  <field name="OFI-GLS-ANX1">
    <type name="string" size="4"/>
    <fms name="OFI_GLS_ANX1" modifier="FLD" row="11" column="63" picture="XXXX" attributes="4242933"/>
  </field>

  <field name="OFI-GLS-ANX2">
    <type name="string" size="4"/>
    <fms name="OFI_GLS_ANX2" modifier="FLD" row="11" column="75" picture="XXXX" attributes="4242933"/>
  </field>

  <field name="OFI-VRF-CCTE" special="VRF">
    <type name="string" size="14"/>
    <fms name="OFI_VRF_CCTE" modifier="FLD" row="13" column="18" picture="XXXXXXXXXXXX-X" attributes="4505061"/>
  </field>

  <field name="OFI-VRF-CCON" special="VRF">
    <type name="string" size="14"/>
    <fms name="OFI_VRF_CCON" modifier="FLD" row="13" column="63" picture="XXXXXXXXXXXX-X" attributes="4505061"/>
  </field>

  <field name="OFI-COD-OREG">
    <type name="string" size="3"/>
    <fms name="OFI_COD_OREG" modifier="FLD" row="15" column="18" picture="XXX" attributes="4242933"/>
  </field>

  <field name="FRM-GLS-OREG">
    <type name="string" size="17"/>
    <fms name="FRM_GLS_OREG" modifier="FLD" row="15" column="26" picture="XXXXXXXXXXXXXXXXX" attributes="2161911"/>
  </field>

  <field name="OFI-COD-OFCO">
    <type name="string" size="3"/>
    <fms name="OFI_COD_OFCO" modifier="FLD" row="15" column="76" picture="XXX" attributes="4242933"/>
  </field>

  <field name="FRM-GLS-GREG">
    <type name="string" size="37"/>
    <fms name="FRM_GLS_GREG" modifier="FLD" row="16" column="6" picture="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="2161911"/>
  </field>

  <field name="FRM-GLS-OFCO">
    <type name="string" size="29"/>
    <fms name="FRM_GLS_OFCO" modifier="FLD" row="16" column="50" picture="XXXXXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="2161911"/>
  </field>

  <field name="OFI-COD-JFOF">
    <type name="string" size="12"/>
    <fms name="OFI_COD_JFOF" modifier="FLD" row="17" column="18" picture="XXXXXXXXXXXX" attributes="4242933"/>
  </field>

  <field name="OFI-FEC-FJFO" special="FEC">
    <type name="date" size="10"/>
    <fms name="OFI_FEC_FJFO" modifier="FLD" row="17" column="46" picture="99-99-9999" attributes="4242933"/>
  </field>

  <field name="OFI-IND-CCOM">
    <type name="char" size="1"/>
    <fms name="OFI_IND_CCOM" modifier="FLD" row="17" column="78" picture="X" attributes="4242933"/>
  </field>

  <field name="FRM-GLS-JFOF">
    <type name="string" size="37"/>
    <fms name="FRM_GLS_JFOF" modifier="FLD" row="18" column="6" picture="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="2161911"/>
  </field>

  <field name="FRM-GLS-CCOM">
    <type name="string" size="16"/>
    <fms name="FRM_GLS_CCOM" modifier="FLD" row="18" column="63" picture="XXXXXXXXXXXXXXXX" attributes="2161911"/>
  </field>

  <field name="OFI-COD-JOOF">
    <type name="string" size="12"/>
    <fms name="OFI_COD_JOOF" modifier="FLD" row="19" column="18" picture="XXXXXXXXXXXX" attributes="4242933"/>
  </field>

  <field name="OFI-FEC-FJOO" special="FEC">
    <type name="date" size="10"/>
    <fms name="OFI_FEC_FJOO" modifier="FLD" row="19" column="46" picture="99-99-9999" attributes="4242933"/>
  </field>

  <field name="OFI-IND-COPE">
    <type name="char" size="1"/>
    <fms name="OFI_IND_COPE" modifier="FLD" row="19" column="78" picture="X" attributes="4242933"/>
  </field>

  <field name="FRM-GLS-JOOF">
    <type name="string" size="37"/>
    <fms name="FRM_GLS_JOOF" modifier="FLD" row="20" column="6" picture="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="2161911"/>
  </field>

  <field name="FRM-GLS-COPE">
    <type name="string" size="16"/>
    <fms name="FRM_GLS_COPE" modifier="FLD" row="20" column="63" picture="XXXXXXXXXXXXXXXX" attributes="2161911"/>
  </field>

  <field name="OFI-FEC-FAPE" special="FEC">
    <type name="date" size="10"/>
    <fms name="OFI_FEC_FAPE" modifier="FLD" row="21" column="18" picture="99-99-9999" attributes="4242933"/>
  </field>

  <field name="OFI-FEC-FCIE" special="FEC">
    <type name="date" size="10"/>
    <fms name="OFI_FEC_FCIE" modifier="FLD" row="21" column="46" picture="99-99-9999" attributes="4242933"/>
  </field>

  <field name="OFI-FEC-FTRN" special="FEC">
    <type name="date" size="10"/>
    <fms name="OFI_FEC_FTRN" modifier="FLD" row="21" column="69" picture="99-99-9999" attributes="4242679"/>
  </field>

  <primary>
    <field name="OFI-COD-OFIC"/>
  </primary>

  <text caption="01. Cod Ofic" row="3" column="2" />
  <text caption="02. Cod Int Comp" row="3" column="33" />
  <text caption="03. Cod Ext" row="3" column="59" />
  <text caption="04. Oficina" row="5" column="2" />
  <text caption="05. Abreviac" row="5" column="59" />
  <text caption="06. Direccion" row="7" column="2" />
  <text caption="07. Comuna" row="7" column="59" />
  <text caption="08. Telex" row="9" column="2" />
  <text caption="09. Plaza" row="9" column="59" />
  <text caption="10. Fonos" row="11" column="2" />
  <text caption="11. Anexos" row="11" column="46" />
  <text caption="12. Cta Cte" row="13" column="2" />
  <text caption="13. Cta Ctble" row="13" column="46" />
  <text caption="14. Regional" row="15" column="2" />
  <text caption="15. Ofic Central Operativa" row="15" column="46" />
  <text caption="16. Jefe Ofic" row="17" column="2" />
  <text caption="17. Desde" row="17" column="33" />
  <text caption="18. Clasif Comer" row="17" column="59" />
  <text caption="19. Jefe Oper" row="19" column="2" />
  <text caption="20. Desde" row="19" column="33" />
  <text caption="21. Clasif Oper" row="19" column="59" />
  <text caption="22. Apertura" row="21" column="2" />
  <text caption="23. Cierre" row="21" column="33" />
  <text caption="24. Mod" row="21" column="59" />

</form>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/form/form_sgc_ddj.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<form xmlns              = "http://cl/bee/genfrmjava/formdef/schema"
      xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation = "http://cl/bee/genfrmjava/formdef/schema formdef.xsd"
      entity             = "SGC_DDJ"
      name               = "DDJ"
      posx               = "1"
      posy               = "23"
      width              = "80">

  <field name="FRM-CAI-IFOL">
    <type name="string" size="4"/>
    <fms name="FRM_IKY_CAI_IFOL" modifier="IKY" row="4" column="26" picture="XXXX" attributes="130549"/>
  </field>

  <field name="FRM-IIC-IFOL">
    <type name="string" size="8"/>
    <fms name="FRM_IKY_IIC_IFOL" modifier="IKY" row="4" column="35" picture="XXXXXXXX" attributes="130549"/>
  </field>

  <field name="DBC-VRF-ICLI" special="VRF">
    <type name="string" size="10"/>
    <fms name="DBC_VRF_ICLI" modifier="FLD" row="6" column="26" picture="XXXXXXXX-X" attributes="64759"/>
  </field>

  <field name="DBC-IDC-ICLI" special="IDC">
    <type name="string" size="5"/>
    <fms name="DBC_IDC_ICLI" modifier="FLD" row="6" column="42" picture="X-XXX" attributes="64759"/>
  </field>

  <field name="DBC-GLS-NOMC">
    <type name="string" size="60"/>
    <fms name="DBC_GLS_NOMC" modifier="FLD" row="9" column="15" picture="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="64759"/>
  </field>

  <field name="FRM-EST-DDJ">
    <type name="char" size="1"/>
    <fms name="FRM_EST_DDJ" modifier="FLD" row="11" column="26" picture="X" attributes="64759"/>
  </field>

  <field name="FRM-GLS-DDJ">
    <type name="string" size="46"/>
    <fms name="FRM_GLS_DDJ" modifier="FLD" row="11" column="29" picture="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="64759"/>
  </field>

  <field name="FRM-CAI-IFOA">
    <type name="string" size="4"/>
    <fms name="FRM_CAI_IFOA" modifier="FLD" row="13" column="26" picture="XXXX" attributes="64759"/>
  </field>

  <field name="FRM-IIC-IFOA">
    <type name="string" size="8"/>
    <fms name="FRM_IIC_IFOA" modifier="FLD" row="13" column="31" picture="XXXXXXXX" attributes="64759"/>
  </field>

  <primary>
    <field name="FRM-CAI-IFOL"/>
    <field name="FRM-IIC-IFOL"/>
  </primary>

  <text caption="Declaracion Jurada  :" row="4" column="2" />
  <text caption="IdC                 :" row="6" column="2" />
  <text caption="Nombre o" row="8" column="2" />
  <text caption="R Social :" row="9" column="2" />
  <text caption="Estado Decl.Jurada  :" row="11" column="2" />
  <text caption="Declaracion Anterior:" row="13" column="2" />

</form>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/form/form_sgc_qc2.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<form xmlns              = "http://cl/bee/genfrmjava/formdef/schema"
      xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation = "http://cl/bee/genfrmjava/formdef/schema formdef.xsd"
      entity             = "SGC_QC2"
      name               = "QC2"
      posx               = "3"
      posy               = "21"
      width              = "80">

  <field name="RCE-COD-SIST">
    <type name="string" size="3"/>
    <fms name="RCE_IKY_COD_SIST" modifier="IKY" row="3" column="13" picture="XXX" attributes="65013"/>
  </field>

  <field name="FRM-GLS-SIST">
    <type name="string" size="20"/>
    <fms name="FRM_GLS_SIST" modifier="FLD" row="3" column="19" picture="XXXXXXXXXXXXXXXXXXXX" attributes="64759"/>
  </field>

  <field name="RCE-COD-ENTI">
    <type name="string" size="3"/>
    <fms name="RCE_IKY_COD_ENTI" modifier="IKY" row="3" column="52" picture="XXX" attributes="2291189"/>
  </field>

  <field name="FRM-GLS-ENTI">
    <type name="string" size="20"/>
    <fms name="FRM_IKY_GLS_ENTI" modifier="IKY" row="3" column="58" picture="XXXXXXXXXXXXXXXXXXXX" attributes="2161911"/>
  </field>

  <field name="FRM-GLS-TNOM">
    <type name="string" size="12"/>
    <fms name="FRM_IKY_GLS_TNOM" modifier="IKY" row="4" column="3" picture="XXXXXXXXXXXX" attributes="64759"/>
  </field>

  <field name="DBC-GLS-NOMC">
    <type name="string" size="60"/>
    <fms name="DBC_AKY_GLS_NOMC" modifier="AKY" row="4" column="18" picture="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="194037"/>
  </field>

  <field name="FRM-GLS-TIDC">
    <type name="string" size="12"/>
    <fms name="FRM_IKY_GLS_TIDC" modifier="IKY" row="5" column="3" picture="XXXXXXXXXXXX" attributes="64759"/>
  </field>

  <field name="DBC-VRF-ICLI" special="VRF">
    <type name="string" size="10"/>
    <fms name="DBC_IKY_VRF_ICLI" modifier="IKY" row="5" column="18" picture="XXXXXXXX-X" attributes="2553317"/>
  </field>

  <field name="DBC-IDC-ICLI" special="IDC">
    <type name="string" size="5"/>
    <fms name="DBC_IKY_IDC_ICLI" modifier="IKY" row="5" column="35" picture="X-XXX" attributes="194037"/>
  </field>

  <field name="FRM-GLS-TOPE">
    <type name="string" size="12"/>
    <fms name="FRM_IKY_GLS_TOPE" modifier="IKY" row="5" column="45" picture="XXXXXXXXXXXX" attributes="64759"/>
  </field>

  <field name="FRM-CAI-IOPE">
    <type name="string" size="4"/>
    <fms name="FRM_IKY_CAI_IOPE" modifier="IKY" row="5" column="60" picture="XXXX" attributes="194037"/>
  </field>

  <field name="FRM-IIC-IOPE">
    <type name="string" size="8"/>
    <fms name="FRM_IKY_IIC_IOPE" modifier="IKY" row="5" column="70" picture="XXXXXXXX" attributes="65013"/>
  </field>

  <field name="FRM-GLS-TFEC">
    <type name="string" size="12"/>
    <fms name="FRM_IKY_GLS_TFEC" modifier="IKY" row="6" column="3" picture="XXXXXXXXXXXX" attributes="64759"/>
  </field>

  <field name="FRM-FEC-FENT" special="FEC">
    <type name="date" size="10"/>
    <fms name="FRM_IKY_FEC_FENT" modifier="IKY" row="6" column="18" picture="99-99-9999" attributes="194037"/>
  </field>

  <field name="FRM-GLS-TNRO">
    <type name="string" size="5"/>
    <fms name="FRM_IKY_GLS_TNRO" modifier="IKY" row="6" column="31" picture="XXXXX" attributes="64759"/>
  </field>

  <field name="FRM-NUM-IENT">
    <type name="integer" size="3" integers="3"/>
    <fms name="FRM_IKY_NUM_IENT" modifier="IKY" row="6" column="39" picture="999" attributes="2020836"/>
  </field>

  <field name="FRM-GLS-TCOD">
    <type name="string" size="12"/>
    <fms name="FRM_IKY_GLS_TCOD" modifier="IKY" row="6" column="45" picture="XXXXXXXXXXXX" attributes="64759"/>
  </field>

  <field name="FRM-COD-IENT">
    <type name="string" size="3"/>
    <fms name="FRM_IKY_COD_IENT" modifier="IKY" row="6" column="60" picture="XXX" attributes="194037"/>
  </field>

  <field name="FRM-GLS-IENT">
    <type name="string" size="12"/>
    <fms name="FRM_GLS_IENT" modifier="FLD" row="6" column="66" picture="XXXXXXXXXXXX" attributes="193783"/>
  </field>

  <field name="FRM-COD-AUTD">
    <type name="string" size="12"/>
    <fms name="FRM_AKY_COD_AUTD" modifier="AKY" row="7" column="11" picture="XXXXXXXXXXXX" attributes="65013"/>
  </field>

  <field name="FRM-FEC-FDES" special="FEC">
    <type name="date" size="10"/>
    <fms name="FRM_AKY_FEC_FDES" modifier="AKY" row="7" column="43" picture="99-99-9999" attributes="65013"/>
  </field>

  <field name="FRM-FEC-FHAS" special="FEC">
    <type name="date" size="10"/>
    <fms name="FRM_AKY_FEC_FHAS" modifier="AKY" row="7" column="68" picture="99-99-9999" attributes="65013"/>
  </field>

  <field name="FRM-CAI-IENT">
    <type name="string" size="4"/>
    <fms name="FRM_AKY_CAI_IENT" modifier="AKY" row="8" column="18" picture="XXXX" attributes="194037"/>
  </field>

  <field name="FRM-IIC-IENT">
    <type name="string" size="8"/>
    <fms name="FRM_AKY_IIC_IENT" modifier="AKY" row="8" column="28" picture="XXXXXXXX" attributes="65013"/>
  </field>

  <array size="3">

    <field name="FRM-CIC-IENT">
      <type name="string" size="12"/>
      <fms name="FRM_CIC_IENT" modifier="FLD" picture="XXXXXXXXXXXX" attributes="193783"/>
      <index>
        <pos row="13" column="4"/>
        <pos row="16" column="4"/>
        <pos row="19" column="4"/>
      </index>
    </field>

    <field name="FRM-FEC-FCMT" special="FEC">
      <type name="date" size="10"/>
      <fms name="FRM_FEC_FCMT" modifier="FLD" picture="99-99-9999" attributes="193783"/>
      <index>
        <pos row="13" column="17"/>
        <pos row="16" column="17"/>
        <pos row="19" column="17"/>
      </index>
    </field>

    <field name="FRM-NUM-GCMT">
      <type name="integer" size="3" integers="3"/>
      <fms name="FRM_NUM_GCMT" modifier="FLD" picture="999" attributes="64759"/>
      <index>
        <pos row="13" column="30"/>
        <pos row="16" column="30"/>
        <pos row="19" column="30"/>
      </index>
    </field>

    <field name="FRM-NUM-CCMT">
      <type name="integer" size="3" integers="3"/>
      <fms name="FRM_NUM_CCMT" modifier="FLD" picture="999" attributes="64759"/>
      <index>
        <pos row="13" column="41"/>
        <pos row="16" column="41"/>
        <pos row="19" column="41"/>
      </index>
    </field>

    <field name="FRM-COD-AUTC">
      <type name="string" size="12"/>
      <fms name="FRM_COD_AUTC" modifier="FLD" picture="XXXXXXXXXXXX" attributes="4242679"/>
      <index>
        <pos row="13" column="48"/>
        <pos row="16" column="48"/>
        <pos row="19" column="48"/>
      </index>
    </field>

    <field name="FRM-COD-TCOM">
      <type name="string" size="12"/>
      <fms name="FRM_COD_TCOM" modifier="FLD" picture="XXXXXXXXXXXX" attributes="4242679"/>
      <index>
        <pos row="13" column="63"/>
        <pos row="16" column="63"/>
        <pos row="19" column="63"/>
      </index>
    </field>

    <field name="FRM-GLS-REFE">
      <type name="string" size="60"/>
      <fms name="FRM_GLS_REFE" modifier="FLD" picture="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="4242679"/>
      <index>
        <pos row="14" column="7"/>
        <pos row="17" column="7"/>
        <pos row="20" column="7"/>
      </index>
    </field>

    <field name="FRM-GLS-KCM1">
      <type name="string" size="60"/>
      <fms name="FRM_GLS_KCM1" modifier="FLD" picture="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="4242679"/>
      <index>
        <pos row="15" column="7"/>
        <pos row="18" column="7"/>
        <pos row="21" column="7"/>
      </index>
    </field>

  </array>

  <primary>
    <field name="RCE-COD-SIST"/>
    <field name="RCE-COD-ENTI"/>
    <field name="FRM-GLS-ENTI"/>
    <field name="FRM-GLS-TNOM"/>
    <field name="FRM-GLS-TIDC"/>
    <field name="DBC-VRF-ICLI"/>
    <field name="DBC-IDC-ICLI"/>
    <field name="FRM-GLS-TOPE"/>
    <field name="FRM-CAI-IOPE"/>
    <field name="FRM-IIC-IOPE"/>
    <field name="FRM-GLS-TFEC"/>
    <field name="FRM-FEC-FENT"/>
    <field name="FRM-GLS-TNRO"/>
    <field name="FRM-NUM-IENT"/>
    <field name="FRM-GLS-TCOD"/>
    <field name="FRM-COD-IENT"/>
  </primary>

  <foreign entity="{{{TODO_foreign_entity}}}">
    <field name="DBC-GLS-NOMC"/>
  </foreign>

  <foreign entity="{{{TODO_foreign_entity}}}">
    <field name="FRM-COD-AUTD"/>
  </foreign>

  <foreign entity="{{{TODO_foreign_entity}}}">
    <field name="FRM-FEC-FDES"/>
  </foreign>

  <foreign entity="{{{TODO_foreign_entity}}}">
    <field name="FRM-FEC-FHAS"/>
  </foreign>

  <foreign entity="{{{TODO_foreign_entity}}}">
    <field name="FRM-CAI-IENT"/>
  </foreign>

  <foreign entity="{{{TODO_foreign_entity}}}">
    <field name="FRM-IIC-IENT"/>
  </foreign>

  <text caption="Cod.Sist" row="3" column="3" />
  <text caption="Tip.Cmt" row="3" column="42" />
  <text caption="Autor" row="7" column="3" />
  <text caption="Fec.Desde" row="7" column="31" />
  <text caption="Fec.Hasta" row="7" column="56" />
  <text caption="Llave Cmt" row="8" column="3" />
  <text caption="Ident.Cmt   Fecha.Cmt  Grup.Cmt  Corr.Cmt   Autor.Cmt      Tip.Cmt" row="10" column="5" />
  <text caption="Referencia" row="11" column="7" />
  <text caption="Llave Cmt" row="12" column="7" />

</form>
