=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/build/schemaorg_apache_xmlbeans/src/formdef.xsd
<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema'
           targetNamespace='http://cl/bee/genfrmjava/formdef/schema'
                     xmlns='http://cl/bee/genfrmjava/formdef/schema'>

 <!-- ========================================================================================== ==
   == form
   == ========================================================================================== -->

 <xsd:element name='form'>

  <xsd:complexType>

   <xsd:sequence minOccurs='1' maxOccurs='unbounded'>
    <xsd:choice>
      <xsd:element ref='field'/>
      <xsd:element ref='array'/>
      <xsd:element ref='primary'/>
      <xsd:element ref='foreign'/>
      <xsd:element ref='text'/>
    </xsd:choice>
   </xsd:sequence>

   <xsd:attribute name='entity' type='xsd:string' use='required'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == field
   == ========================================================================================== -->

 <xsd:element name='field'>

  <xsd:complexType>

   <xsd:sequence minOccurs='0' maxOccurs='unbounded'>
    <xsd:choice>
      <xsd:element ref='type'/>
      <xsd:element ref='fms'/>
      <xsd:element ref='default'/>
      <xsd:element ref='index'/>
    </xsd:choice>
   </xsd:sequence>

   <xsd:attribute name='name'    type='xsd:string' use='required'/>
   <xsd:attribute name='special' type='xsd:string' default=''/>
  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == array
   == ========================================================================================== -->

 <xsd:element name='array'>

  <xsd:complexType>

   <xsd:sequence>
    <xsd:element ref='field' maxOccurs='unbounded'/>
   </xsd:sequence>

   <xsd:attribute name='size' type='xsd:unsignedInt' use='required'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == primary
   == ========================================================================================== -->

 <xsd:element name='primary'>

  <xsd:complexType>

   <xsd:sequence>
    <xsd:element ref='field' maxOccurs='unbounded'/>
   </xsd:sequence>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == foreign
   == ========================================================================================== -->

 <xsd:element name='foreign'>

  <xsd:complexType>

   <xsd:sequence>
    <xsd:element ref='field' maxOccurs='unbounded'/>
   </xsd:sequence>

   <xsd:attribute name='entity' type='xsd:string' use='required'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == text
   == ========================================================================================== -->

 <xsd:element name='text'>

  <xsd:complexType>

   <xsd:attribute name='caption' type='xsd:string'      use='required'/>
   <xsd:attribute name='row'     type='xsd:unsignedInt' use='required'/>
   <xsd:attribute name='column'  type='xsd:unsignedInt' use='required'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == type
   == ========================================================================================== -->

 <xsd:element name='type'>

  <xsd:complexType>

   <xsd:attribute name='name'     type='TipoType'        use='required'/>
   <xsd:attribute name='size'     type='xsd:unsignedInt' use='required'/>
   <xsd:attribute name='integers' type='xsd:unsignedInt' default='0'/>
   <xsd:attribute name='decimals' type='xsd:unsignedInt' default='0'/>
   <xsd:attribute name='sign'     type='YesNoType'       default='no'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == TipoType
   == ========================================================================================== -->

 <xsd:simpleType name='TipoType'>

  <xsd:restriction base='xsd:string'>
   <xsd:enumeration value='integer'/>
   <xsd:enumeration value='long'   />
   <xsd:enumeration value='double' />
   <xsd:enumeration value='char'   />
   <xsd:enumeration value='boolean'/>
   <xsd:enumeration value='string' />
   <xsd:enumeration value='date'   />
  </xsd:restriction>

 </xsd:simpleType>

 <!-- ========================================================================================== ==
   == YesNoType
   == ========================================================================================== -->

 <xsd:simpleType name='YesNoType'>

  <xsd:restriction base='xsd:string'>
   <xsd:enumeration value='yes'/>
   <xsd:enumeration value='no' />
  </xsd:restriction>

 </xsd:simpleType>

 <!-- ========================================================================================== ==
   == fms
   == ========================================================================================== -->

 <xsd:element name='fms'>

  <xsd:complexType>

   <xsd:attribute name='name'       type='xsd:string'      use='required'/>
   <xsd:attribute name='modifier'   type='ModifierType'    use='required'/>
   <xsd:attribute name='row'        type='xsd:unsignedInt' default='0'/>
   <xsd:attribute name='column'     type='xsd:unsignedInt' default='0'/>
   <xsd:attribute name='picture'    type='xsd:string'      use='required'/>
   <xsd:attribute name='attributes' type='xsd:unsignedInt' use='required'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == ModifierType
   == ========================================================================================== -->

 <xsd:simpleType name='ModifierType'>

  <xsd:restriction base='xsd:string'>
   <xsd:enumeration value='IKY'/>
   <xsd:enumeration value='MKY'/>
   <xsd:enumeration value='AKY'/>
   <xsd:enumeration value='FLD'/>
  </xsd:restriction>

 </xsd:simpleType>

 <!-- ========================================================================================== ==
   == default
   == ========================================================================================== -->

 <xsd:element name='default'>

  <xsd:complexType>

   <xsd:attribute name='value' type='xsd:string'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == index
   == ========================================================================================== -->

 <xsd:element name='index'>

  <xsd:complexType>

   <xsd:sequence>
    <xsd:element ref='pos' maxOccurs='unbounded'/>
   </xsd:sequence>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == pos
   == ========================================================================================== -->

 <xsd:element name='pos'>

  <xsd:complexType>

   <xsd:attribute name='row'    type='xsd:unsignedInt'/>
   <xsd:attribute name='column' type='xsd:unsignedInt'/>

  </xsd:complexType>

 </xsd:element>


</xsd:schema>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/form/form_sgc_cfc.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<form xmlns              = "http://cl/bee/genfrmjava/formdef/schema"
      xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation = "http://cl/bee/genfrmjava/formdef/schema formdef.xsd"
      entity             = "SGC_CFC"
      name               = "CFC"
      posx               = "1"
      posy               = "23"
      width              = "80">

  <field name="DBC-VRF-ICLI" special="VRF">
    <type name="string" size="10"/>
    <fms name="DBC_IKY_VRF_ICLI" modifier="IKY" row="3" column="23" picture="XXXXXXXX-X" attributes="65013"/>
  </field>

  <field name="DBC-IDC-ICLI" special="IDC">
    <type name="string" size="5"/>
    <fms name="DBC_IKY_IDC_ICLI" modifier="IKY" row="3" column="40" picture="X-XXX" attributes="65013"/>
  </field>

  <field name="FRM-GLS-NOMC">
    <type name="string" size="33"/>
    <fms name="FRM_GLS_NOMC" modifier="FLD" row="4" column="23" picture="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="64759"/>
  </field>

  <field name="RPR-COD-TFRM">
    <type name="string" size="2"/>
    <fms name="RPR_IKY_COD_TFRM" modifier="IKY" row="5" column="23" picture="XX" attributes="65013"/>
  </field>

  <field name="FRM-GLS-LDOC">
    <type name="string" size="40"/>
    <fms name="FRM_GLS_LDOC" modifier="FLD" row="5" column="31" picture="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="64759"/>
  </field>

  <field name="RPR-IND-ESTA">
    <type name="char" size="1"/>
    <fms name="RPR_IKY_IND_ESTA" modifier="IKY" row="6" column="23" picture="X" attributes="65013"/>
  </field>

  <field name="FRM-GLS-ESTA">
    <type name="string" size="15"/>
    <fms name="FRM_GLS_ESTA" modifier="FLD" row="6" column="31" picture="XXXXXXXXXXXXXXX" attributes="64759"/>
  </field>

  <field name="FRM-IND-HMAS">
    <type name="char" size="1"/>
    <fms name="FRM_MKY_IND_HMAS" modifier="MKY" row="7" column="5" picture="X" attributes="65013"/>
  </field>

  <field name="FRM-CAI-IFOR">
    <type name="string" size="4"/>
    <fms name="FRM_MKY_CAI_IFOR" modifier="MKY" row="7" column="12" picture="XXXX" attributes="65013"/>
  </field>

  <field name="FRM-IIC-IFOR">
    <type name="integer" size="8" integers="8"/>
    <fms name="FRM_MKY_IIC_IFOR" modifier="MKY" row="7" column="21" picture="99999999" attributes="1891812"/>
  </field>

  <array size="10">

    <field name="FRM-CAI-IFOL">
      <type name="string" size="4"/>
      <fms name="FRM_CAI_IFOL" modifier="FLD" picture="XXXX" attributes="64759"/>
      <index>
        <pos row="11" column="3"/>
        <pos row="12" column="3"/>
        <pos row="13" column="3"/>
        <pos row="14" column="3"/>
        <pos row="15" column="3"/>
        <pos row="16" column="3"/>
        <pos row="17" column="3"/>
        <pos row="18" column="3"/>
        <pos row="19" column="3"/>
        <pos row="20" column="3"/>
      </index>
    </field>

    <field name="FRM-IIC-IFOL">
      <type name="integer" size="8" integers="8"/>
      <fms name="FRM_IIC_IFOL" modifier="FLD" picture="99999999" attributes="1891558"/>
      <index>
        <pos row="11" column="8"/>
        <pos row="12" column="8"/>
        <pos row="13" column="8"/>
        <pos row="14" column="8"/>
        <pos row="15" column="8"/>
        <pos row="16" column="8"/>
        <pos row="17" column="8"/>
        <pos row="18" column="8"/>
        <pos row="19" column="8"/>
        <pos row="20" column="8"/>
      </index>
    </field>

    <field name="FRM-IND-ESTA">
      <type name="char" size="1"/>
      <fms name="FRM_IND_ESTA" modifier="FLD" picture="X" attributes="64759"/>
      <index>
        <pos row="11" column="20"/>
        <pos row="12" column="20"/>
        <pos row="13" column="20"/>
        <pos row="14" column="20"/>
        <pos row="15" column="20"/>
        <pos row="16" column="20"/>
        <pos row="17" column="20"/>
        <pos row="18" column="20"/>
        <pos row="19" column="20"/>
        <pos row="20" column="20"/>
      </index>
    </field>

    <field name="FRM-COD-TFRM">
      <type name="string" size="2"/>
      <fms name="FRM_COD_TFRM" modifier="FLD" picture="XX" attributes="64759"/>
      <index>
        <pos row="11" column="29"/>
        <pos row="12" column="29"/>
        <pos row="13" column="29"/>
        <pos row="14" column="29"/>
        <pos row="15" column="29"/>
        <pos row="16" column="29"/>
        <pos row="17" column="29"/>
        <pos row="18" column="29"/>
        <pos row="19" column="29"/>
        <pos row="20" column="29"/>
      </index>
    </field>

    <field name="FRM-FEC-FRPR" special="FEC">
      <type name="date" size="8" integers="8"/>
      <fms name="FRM_FEC_FRPR" modifier="FLD" picture="99999999" attributes="64759"/>
      <index>
        <pos row="11" column="40"/>
        <pos row="12" column="40"/>
        <pos row="13" column="40"/>
        <pos row="14" column="40"/>
        <pos row="15" column="40"/>
        <pos row="16" column="40"/>
        <pos row="17" column="40"/>
        <pos row="18" column="40"/>
        <pos row="19" column="40"/>
        <pos row="20" column="40"/>
      </index>
    </field>

  </array>

  <primary>
    <field name="DBC-VRF-ICLI"/>
    <field name="DBC-IDC-ICLI"/>
    <field name="RPR-COD-TFRM"/>
    <field name="RPR-IND-ESTA"/>
  </primary>

  <foreign entity="{{{TODO_foreign_entity}}}">
    <field name="FRM-IND-HMAS"/>
  </foreign>

  <foreign entity="{{{TODO_foreign_entity}}}">
    <field name="FRM-CAI-IFOR"/>
  </foreign>

  <foreign entity="{{{TODO_foreign_entity}}}">
    <field name="FRM-IIC-IFOR"/>
  </foreign>

  <text caption="IdC Cliente" row="3" column="3" />
  <text caption="Nombre/R.Social" row="4" column="3" />
  <text caption="Doc.Recibidos" row="5" column="3" />
  <text caption="Estado Formulario" row="6" column="3" />
  <text caption="Folio          Estado  Doc.Recib.  Fecha Recepcion" row="9" column="3" />
  <text caption="---------------------------------------------------------------------------" row="10" column="3" />

</form>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/form/form_dap_ccc.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<form xmlns              = "http://cl/bee/genfrmjava/formdef/schema"
      xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation = "http://cl/bee/genfrmjava/formdef/schema formdef.xsd"
      entity             = "DAP_CCC"
      name               = "CCC"
      posx               = "1"
      posy               = "23"
      width              = "80">

  <field name="DBC-GLS-NOMC" special="GLS">
    <type name="string" size="56"/>
    <fms name="DBC_AKY_GLS_NOMC" modifier="AKY" row="3" column="21" picture="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="65013"/>
  </field>

  <field name="DBC-VRF-ICLI" special="VRF">
    <type name="string" size="10"/>
    <fms name="DBC_AKY_VRF_ICLI" modifier="AKY" row="4" column="21" picture="XXXXXXXX-X" attributes="65013"/>
  </field>

  <field name="DBC-IDC-ICLI" special="IDC">
    <type name="string" size="5"/>
    <fms name="DBC_AKY_IDC_ICLI" modifier="AKY" row="4" column="38" picture="X-XXX" attributes="65013"/>
  </field>

  <array size="6">

    <field name="FRM-VAL-TOTA">
      <type name="double" size="20" integers="12" decimals="4" sign="no" />
      <fms name="FRM_VAL_TOTA" modifier="FLD" picture="999.999.999.999,9999" attributes="64759"/>
      <index>
        <pos row="6" column="21"/>
        <pos row="6" column="51"/>
        <pos row="7" column="21"/>
        <pos row="7" column="51"/>
        <pos row="8" column="21"/>
        <pos row="8" column="51"/>
      </index>
    </field>

    <field name="FRM-GLS-TOTA" special="GLS">
      <type name="string" size="5"/>
      <fms name="FRM_GLS_TOTA" modifier="FLD" picture="XXXXX" attributes="64759"/>
      <index>
        <pos row="6" column="45"/>
        <pos row="6" column="75"/>
        <pos row="7" column="45"/>
        <pos row="7" column="75"/>
        <pos row="8" column="45"/>
        <pos row="8" column="75"/>
      </index>
    </field>

  </array>

  <array size="11">

    <field name="FRM-CAI-IOPD">
      <type name="string" size="4"/>
      <fms name="FRM_CAI_IOPD" modifier="FLD" picture="XXXX" attributes="64759"/>
      <index>
        <pos row="11" column="2"/>
        <pos row="12" column="2"/>
        <pos row="13" column="2"/>
        <pos row="14" column="2"/>
        <pos row="15" column="2"/>
        <pos row="16" column="2"/>
        <pos row="17" column="2"/>
        <pos row="18" column="2"/>
        <pos row="19" column="2"/>
        <pos row="20" column="2"/>
        <pos row="21" column="2"/>
      </index>
    </field>

    <field name="FRM-IIC-IOPD">
      <type name="integer" size="8" integers="8"/>
      <fms name="FRM_IIC_IOPD" modifier="FLD" picture="99999999" attributes="64759"/>
      <index>
        <pos row="11" column="7"/>
        <pos row="12" column="7"/>
        <pos row="13" column="7"/>
        <pos row="14" column="7"/>
        <pos row="15" column="7"/>
        <pos row="16" column="7"/>
        <pos row="17" column="7"/>
        <pos row="18" column="7"/>
        <pos row="19" column="7"/>
        <pos row="20" column="7"/>
        <pos row="21" column="7"/>
      </index>
    </field>

    <field name="FRM-IND-VENC">
      <type name="char" size="1"/>
      <fms name="FRM_IND_VENC" modifier="FLD" picture="X" attributes="64759"/>
      <index>
        <pos row="11" column="16"/>
        <pos row="12" column="16"/>
        <pos row="13" column="16"/>
        <pos row="14" column="16"/>
        <pos row="15" column="16"/>
        <pos row="16" column="16"/>
        <pos row="17" column="16"/>
        <pos row="18" column="16"/>
        <pos row="19" column="16"/>
        <pos row="20" column="16"/>
        <pos row="21" column="16"/>
      </index>
    </field>

    <field name="FRM-GLS-COPD" special="GLS">
      <type name="string" size="21"/>
      <fms name="FRM_GLS_COPD" modifier="FLD" picture="XXXXXXXXXXXXXXXXXXXXX" attributes="64759"/>
      <index>
        <pos row="11" column="18"/>
        <pos row="12" column="18"/>
        <pos row="13" column="18"/>
        <pos row="14" column="18"/>
        <pos row="15" column="18"/>
        <pos row="16" column="18"/>
        <pos row="17" column="18"/>
        <pos row="18" column="18"/>
        <pos row="19" column="18"/>
        <pos row="20" column="18"/>
        <pos row="21" column="18"/>
      </index>
    </field>

    <field name="FRM-DMA-FREA" special="FEC">
      <type name="date" size="6" integers="6"/>
      <fms name="FRM_DMA_FREA" modifier="FLD" picture="999999" attributes="64759"/>
      <index>
        <pos row="11" column="40"/>
        <pos row="12" column="40"/>
        <pos row="13" column="40"/>
        <pos row="14" column="40"/>
        <pos row="15" column="40"/>
        <pos row="16" column="40"/>
        <pos row="17" column="40"/>
        <pos row="18" column="40"/>
        <pos row="19" column="40"/>
        <pos row="20" column="40"/>
        <pos row="21" column="40"/>
      </index>
    </field>

    <field name="FRM-DMA-FPVC" special="FEC">
      <type name="date" size="6" integers="6"/>
      <fms name="FRM_DMA_FPVC" modifier="FLD" picture="999999" attributes="64759"/>
      <index>
        <pos row="11" column="47"/>
        <pos row="12" column="47"/>
        <pos row="13" column="47"/>
        <pos row="14" column="47"/>
        <pos row="15" column="47"/>
        <pos row="16" column="47"/>
        <pos row="17" column="47"/>
        <pos row="18" column="47"/>
        <pos row="19" column="47"/>
        <pos row="20" column="47"/>
        <pos row="21" column="47"/>
      </index>
    </field>

    <field name="FRM-VAL-CAPT">
      <type name="double" size="19" integers="11" decimals="4" sign="no" />
      <fms name="FRM_VAL_CAPT" modifier="FLD" picture="99.999.999.999,9999" attributes="64759"/>
      <index>
        <pos row="11" column="54"/>
        <pos row="12" column="54"/>
        <pos row="13" column="54"/>
        <pos row="14" column="54"/>
        <pos row="15" column="54"/>
        <pos row="16" column="54"/>
        <pos row="17" column="54"/>
        <pos row="18" column="54"/>
        <pos row="19" column="54"/>
        <pos row="20" column="54"/>
        <pos row="21" column="54"/>
      </index>
    </field>

    <field name="FRM-GLS-VCAM" special="GLS">
      <type name="string" size="5"/>
      <fms name="FRM_GLS_VCAM" modifier="FLD" picture="XXXXX" attributes="64759"/>
      <index>
        <pos row="11" column="74"/>
        <pos row="12" column="74"/>
        <pos row="13" column="74"/>
        <pos row="14" column="74"/>
        <pos row="15" column="74"/>
        <pos row="16" column="74"/>
        <pos row="17" column="74"/>
        <pos row="18" column="74"/>
        <pos row="19" column="74"/>
        <pos row="20" column="74"/>
        <pos row="21" column="74"/>
      </index>
    </field>

  </array>

  <foreign entity="{{{TODO_foreign_entity}}}">
    <field name="DBC-GLS-NOMC"/>
  </foreign>

  <foreign entity="{{{TODO_foreign_entity}}}">
    <field name="DBC-VRF-ICLI"/>
  </foreign>

  <foreign entity="{{{TODO_foreign_entity}}}">
    <field name="DBC-IDC-ICLI"/>
  </foreign>

  <text caption="01. Cliente" row="3" column="2" />
  <text caption="02. IdC Cliente" row="4" column="2" />
  <text caption="Totales x Moneda" row="6" column="2" />
  <text caption="Nro Operac.   V Clase                 F.Cap  F.Ven          Monto Capt. Moneda" row="9" column="2" />
  <text caption="------------------------------------------------------------------------------" row="10" column="2" />

</form>
