=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/build/schemaorg_apache_xmlbeans/src/formdef.xsd
<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema'
           targetNamespace='http://cl/bee/genfrmjava/formdef/schema'
                     xmlns='http://cl/bee/genfrmjava/formdef/schema'>

 <!-- ========================================================================================== ==
   == form
   == ========================================================================================== -->

 <xsd:element name='form'>

  <xsd:complexType>

   <xsd:sequence minOccurs='1' maxOccurs='unbounded'>
    <xsd:choice>
      <xsd:element ref='field'/>
      <xsd:element ref='array'/>
      <xsd:element ref='primary'/>
      <xsd:element ref='foreign'/>
      <xsd:element ref='text'/>
    </xsd:choice>
   </xsd:sequence>

   <xsd:attribute name='entity' type='xsd:string' use='required'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == field
   == ========================================================================================== -->

 <xsd:element name='field'>

  <xsd:complexType>

   <xsd:sequence minOccurs='0' maxOccurs='unbounded'>
    <xsd:choice>
      <xsd:element ref='type'/>
      <xsd:element ref='fms'/>
      <xsd:element ref='default'/>
      <xsd:element ref='index'/>
    </xsd:choice>
   </xsd:sequence>

   <xsd:attribute name='name'    type='xsd:string' use='required'/>
   <xsd:attribute name='special' type='xsd:string' default=''/>
  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == array
   == ========================================================================================== -->

 <xsd:element name='array'>

  <xsd:complexType>

   <xsd:sequence>
    <xsd:element ref='field' maxOccurs='unbounded'/>
   </xsd:sequence>

   <xsd:attribute name='size' type='xsd:unsignedInt' use='required'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == primary
   == ========================================================================================== -->

 <xsd:element name='primary'>

  <xsd:complexType>

   <xsd:sequence>
    <xsd:element ref='field' maxOccurs='unbounded'/>
   </xsd:sequence>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == foreign
   == ========================================================================================== -->

 <xsd:element name='foreign'>

  <xsd:complexType>

   <xsd:sequence>
    <xsd:element ref='field' maxOccurs='unbounded'/>
   </xsd:sequence>

   <xsd:attribute name='entity' type='xsd:string' use='required'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == text
   == ========================================================================================== -->

 <xsd:element name='text'>

  <xsd:complexType>

   <xsd:attribute name='caption' type='xsd:string'      use='required'/>
   <xsd:attribute name='row'     type='xsd:unsignedInt' use='required'/>
   <xsd:attribute name='column'  type='xsd:unsignedInt' use='required'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == type
   == ========================================================================================== -->

 <xsd:element name='type'>

  <xsd:complexType>

   <xsd:attribute name='name'     type='TipoType'        use='required'/>
   <xsd:attribute name='size'     type='xsd:unsignedInt' use='required'/>
   <xsd:attribute name='integers' type='xsd:unsignedInt' default='0'/>
   <xsd:attribute name='decimals' type='xsd:unsignedInt' default='0'/>
   <xsd:attribute name='sign'     type='YesNoType'       default='no'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == TipoType
   == ========================================================================================== -->

 <xsd:simpleType name='TipoType'>

  <xsd:restriction base='xsd:string'>
   <xsd:enumeration value='integer'/>
   <xsd:enumeration value='long'   />
   <xsd:enumeration value='double' />
   <xsd:enumeration value='char'   />
   <xsd:enumeration value='boolean'/>
   <xsd:enumeration value='string' />
   <xsd:enumeration value='date'   />
  </xsd:restriction>

 </xsd:simpleType>

 <!-- ========================================================================================== ==
   == YesNoType
   == ========================================================================================== -->

 <xsd:simpleType name='YesNoType'>

  <xsd:restriction base='xsd:string'>
   <xsd:enumeration value='yes'/>
   <xsd:enumeration value='no' />
  </xsd:restriction>

 </xsd:simpleType>

 <!-- ========================================================================================== ==
   == fms
   == ========================================================================================== -->

 <xsd:element name='fms'>

  <xsd:complexType>

   <xsd:attribute name='name'       type='xsd:string'      use='required'/>
   <xsd:attribute name='modifier'   type='ModifierType'    use='required'/>
   <xsd:attribute name='row'        type='xsd:unsignedInt' default='0'/>
   <xsd:attribute name='column'     type='xsd:unsignedInt' default='0'/>
   <xsd:attribute name='picture'    type='xsd:string'      use='required'/>
   <xsd:attribute name='attributes' type='xsd:unsignedInt' use='required'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == ModifierType
   == ========================================================================================== -->

 <xsd:simpleType name='ModifierType'>

  <xsd:restriction base='xsd:string'>
   <xsd:enumeration value='IKY'/>
   <xsd:enumeration value='MKY'/>
   <xsd:enumeration value='AKY'/>
   <xsd:enumeration value='FLD'/>
  </xsd:restriction>

 </xsd:simpleType>

 <!-- ========================================================================================== ==
   == default
   == ========================================================================================== -->

 <xsd:element name='default'>

  <xsd:complexType>

   <xsd:attribute name='value' type='xsd:string'/>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == index
   == ========================================================================================== -->

 <xsd:element name='index'>

  <xsd:complexType>

   <xsd:sequence>
    <xsd:element ref='pos' maxOccurs='unbounded'/>
   </xsd:sequence>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == pos
   == ========================================================================================== -->

 <xsd:element name='pos'>

  <xsd:complexType>

   <xsd:attribute name='row'    type='xsd:unsignedInt'/>
   <xsd:attribute name='column' type='xsd:unsignedInt'/>

  </xsd:complexType>

 </xsd:element>


</xsd:schema>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/form/form_sgc_qcm.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<form xmlns              = "http://cl/bee/genfrmjava/formdef/schema"
      xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation = "http://cl/bee/genfrmjava/formdef/schema formdef.xsd"
      entity             = "SGC_QCM"
      name               = "QCM"
      posx               = "3"
      posy               = "21"
      width              = "80">

  <field name="RCE-COD-ENTI">
    <type name="string" size="3"/>
    <fms name="RCE_IKY_COD_ENTI" modifier="IKY" row="4" column="19" picture="XXX" attributes="2291189"/>
  </field>

  <field name="FRM-GLS-ENTI">
    <type name="string" size="40"/>
    <fms name="FRM_IKY_GLS_ENTI" modifier="IKY" row="4" column="25" picture="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="2161911"/>
  </field>

  <field name="FRM-GLS-TNOM">
    <type name="string" size="12"/>
    <fms name="FRM_IKY_GLS_TNOM" modifier="IKY" row="5" column="4" picture="XXXXXXXXXXXX" attributes="64759"/>
  </field>

  <field name="DBC-GLS-NOMC">
    <type name="string" size="60"/>
    <fms name="DBC_AKY_GLS_NOMC" modifier="AKY" row="5" column="19" picture="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="194037"/>
  </field>

  <field name="FRM-GLS-TIDC">
    <type name="string" size="12"/>
    <fms name="FRM_IKY_GLS_TIDC" modifier="IKY" row="6" column="4" picture="XXXXXXXXXXXX" attributes="64759"/>
  </field>

  <field name="DBC-VRF-ICLI" special="VRF">
    <type name="string" size="10"/>
    <fms name="DBC_IKY_VRF_ICLI" modifier="IKY" row="6" column="19" picture="XXXXXXXX-X" attributes="2553317"/>
  </field>

  <field name="DBC-IDC-ICLI" special="IDC">
    <type name="string" size="5"/>
    <fms name="DBC_IKY_IDC_ICLI" modifier="IKY" row="6" column="36" picture="X-XXX" attributes="194037"/>
  </field>

  <field name="FRM-GLS-TOPE">
    <type name="string" size="12"/>
    <fms name="FRM_IKY_GLS_TOPE" modifier="IKY" row="6" column="46" picture="XXXXXXXXXXXX" attributes="64759"/>
  </field>

  <field name="FRM-CAI-IOPE">
    <type name="string" size="4"/>
    <fms name="FRM_IKY_CAI_IOPE" modifier="IKY" row="6" column="61" picture="XXXX" attributes="194037"/>
  </field>

  <field name="FRM-IIC-IOPE">
    <type name="string" size="8"/>
    <fms name="FRM_IKY_IIC_IOPE" modifier="IKY" row="6" column="71" picture="XXXXXXXX" attributes="65013"/>
  </field>

  <field name="FRM-GLS-TFEC">
    <type name="string" size="12"/>
    <fms name="FRM_IKY_GLS_TFEC" modifier="IKY" row="7" column="4" picture="XXXXXXXXXXXX" attributes="64759"/>
  </field>

  <field name="FRM-FEC-FENT" special="FEC">
    <type name="date" size="10"/>
    <fms name="FRM_IKY_FEC_FENT" modifier="IKY" row="7" column="19" picture="99-99-9999" attributes="194037"/>
  </field>

  <field name="FRM-GLS-TNRO">
    <type name="string" size="5"/>
    <fms name="FRM_IKY_GLS_TNRO" modifier="IKY" row="7" column="32" picture="XXXXX" attributes="64759"/>
  </field>

  <field name="FRM-NUM-IENT">
    <type name="integer" size="3" integers="3"/>
    <fms name="FRM_IKY_NUM_IENT" modifier="IKY" row="7" column="40" picture="999" attributes="2020836"/>
  </field>

  <field name="FRM-GLS-TCOD">
    <type name="string" size="12"/>
    <fms name="FRM_IKY_GLS_TCOD" modifier="IKY" row="7" column="46" picture="XXXXXXXXXXXX" attributes="64759"/>
  </field>

  <field name="FRM-COD-IENT">
    <type name="string" size="3"/>
    <fms name="FRM_IKY_COD_IENT" modifier="IKY" row="7" column="61" picture="XXX" attributes="194037"/>
  </field>

  <field name="FRM-GLS-IENT">
    <type name="string" size="12"/>
    <fms name="FRM_GLS_IENT" modifier="FLD" row="7" column="67" picture="XXXXXXXXXXXX" attributes="193783"/>
  </field>

  <array size="5">

    <field name="FRM-COD-ENTI">
      <type name="string" size="3"/>
      <fms name="FRM_COD_ENTI" modifier="FLD" picture="XXX" attributes="64759"/>
      <index>
        <pos row="12" column="4"/>
        <pos row="14" column="4"/>
        <pos row="16" column="4"/>
        <pos row="18" column="4"/>
        <pos row="20" column="4"/>
      </index>
    </field>

    <field name="FRM-NUM-GCMT">
      <type name="integer" size="1" integers="1"/>
      <fms name="FRM_NUM_GCMT" modifier="FLD" picture="9" attributes="193783"/>
      <index>
        <pos row="12" column="14"/>
        <pos row="14" column="14"/>
        <pos row="16" column="14"/>
        <pos row="18" column="14"/>
        <pos row="20" column="14"/>
      </index>
    </field>

    <field name="FRM-CIC-IENT">
      <type name="string" size="12"/>
      <fms name="FRM_CIC_IENT" modifier="FLD" picture="XXXXXXXXXXXX" attributes="193783"/>
      <index>
        <pos row="12" column="17"/>
        <pos row="14" column="17"/>
        <pos row="16" column="17"/>
        <pos row="18" column="17"/>
        <pos row="20" column="17"/>
      </index>
    </field>

    <field name="FRM-FEC-FCMT" special="FEC">
      <type name="date" size="10"/>
      <fms name="FRM_FEC_FCMT" modifier="FLD" picture="99-99-9999" attributes="193783"/>
      <index>
        <pos row="12" column="30"/>
        <pos row="14" column="30"/>
        <pos row="16" column="30"/>
        <pos row="18" column="30"/>
        <pos row="20" column="30"/>
      </index>
    </field>

    <field name="FRM-COD-AUTC">
      <type name="string" size="12"/>
      <fms name="FRM_COD_AUTC" modifier="FLD" picture="XXXXXXXXXXXX" attributes="4242679"/>
      <index>
        <pos row="12" column="41"/>
        <pos row="14" column="41"/>
        <pos row="16" column="41"/>
        <pos row="18" column="41"/>
        <pos row="20" column="41"/>
      </index>
    </field>

    <field name="FRM-GLS-IENX">
      <type name="string" size="26"/>
      <fms name="FRM_GLS_IENX" modifier="FLD" picture="XXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="64759"/>
      <index>
        <pos row="12" column="54"/>
        <pos row="14" column="54"/>
        <pos row="16" column="54"/>
        <pos row="18" column="54"/>
        <pos row="20" column="54"/>
      </index>
    </field>

    <field name="FRM-COD-SIST">
      <type name="string" size="3"/>
      <fms name="FRM_COD_SIST" modifier="FLD" picture="XXX" attributes="64759"/>
      <index>
        <pos row="13" column="6"/>
        <pos row="15" column="6"/>
        <pos row="17" column="6"/>
        <pos row="19" column="6"/>
        <pos row="21" column="6"/>
      </index>
    </field>

    <field name="FRM-GLS-REFE">
      <type name="string" size="60"/>
      <fms name="FRM_GLS_REFE" modifier="FLD" picture="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="4242679"/>
      <index>
        <pos row="13" column="16"/>
        <pos row="15" column="16"/>
        <pos row="17" column="16"/>
        <pos row="19" column="16"/>
        <pos row="21" column="16"/>
      </index>
    </field>

  </array>

  <primary>
    <field name="RCE-COD-ENTI"/>
    <field name="FRM-GLS-ENTI"/>
    <field name="FRM-GLS-TNOM"/>
    <field name="FRM-GLS-TIDC"/>
    <field name="DBC-VRF-ICLI"/>
    <field name="DBC-IDC-ICLI"/>
    <field name="FRM-GLS-TOPE"/>
    <field name="FRM-CAI-IOPE"/>
    <field name="FRM-IIC-IOPE"/>
    <field name="FRM-GLS-TFEC"/>
    <field name="FRM-FEC-FENT"/>
    <field name="FRM-GLS-TNRO"/>
    <field name="FRM-NUM-IENT"/>
    <field name="FRM-GLS-TCOD"/>
    <field name="FRM-COD-IENT"/>
  </primary>

  <foreign entity="{{{TODO_foreign_entity}}}">
    <field name="DBC-GLS-NOMC"/>
  </foreign>

  <text caption="Tipo Coment" row="4" column="4" />
  <text caption="Tip.Cmt Nro.Cmt Ident.Cmt  Fecha.Cmt  Autor.Cmt   Identif. Entidad" row="9" column="4" />
  <text caption="Cod.Sist    Referencia" row="10" column="6" />
  <text caption="----------------------------------------------------------------------------" row="11" column="4" />

</form>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/form/form_sgc_cac.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<form xmlns              = "http://cl/bee/genfrmjava/formdef/schema"
      xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation = "http://cl/bee/genfrmjava/formdef/schema formdef.xsd"
      entity             = "SGC_CAC"
      name               = "CAC"
      posx               = "1"
      posy               = "23"
      width              = "80">

  <field name="CAC-COD-CPTO">
    <type name="string" size="12"/>
    <fms name="CAC_IKY_COD_CPTO" modifier="IKY" row="4" column="15" picture="XXXXXXXXXXXX" attributes="259573"/>
  </field>

  <field name="FRM-GLS-CPTO">
    <type name="string" size="41"/>
    <fms name="FRM_GLS_CPTO" modifier="FLD" row="4" column="30" picture="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="64759"/>
  </field>

  <field name="DBC-VRF-ICLI" special="VRF">
    <type name="string" size="10"/>
    <fms name="DBC_IKY_VRF_ICLI" modifier="IKY" row="5" column="15" picture="XXXXXXXX-X" attributes="259573"/>
  </field>

  <field name="DBC-IDC-ICLI" special="IDC">
    <type name="string" size="5"/>
    <fms name="DBC_IKY_IDC_ICLI" modifier="IKY" row="5" column="32" picture="X-XXX" attributes="194037"/>
  </field>

  <field name="CAC-FEC-FINI" special="FEC">
    <type name="date" size="8" integers="8"/>
    <fms name="CAC_IKY_FEC_FINI" modifier="IKY" row="5" column="51" picture="99999999" attributes="194037"/>
  </field>

  <field name="CAC-HRA-HINI">
    <type name="integer" size="6" integers="6"/>
    <fms name="CAC_IKY_HRA_HINI" modifier="IKY" row="5" column="72" picture="999999" attributes="194037"/>
  </field>

  <field name="CAC-IND-VIGE">
    <type name="char" size="1"/>
    <fms name="CAC_IND_VIGE" modifier="FLD" row="7" column="17" picture="X" attributes="65013"/>
  </field>

  <field name="CAC-FEC-FTER" special="FEC">
    <type name="date" size="8" integers="8"/>
    <fms name="CAC_FEC_FTER" modifier="FLD" row="7" column="51" picture="99999999" attributes="65013"/>
  </field>

  <field name="CAC-HRA-HTER">
    <type name="integer" size="6" integers="6"/>
    <fms name="CAC_HRA_HTER" modifier="FLD" row="7" column="72" picture="999999" attributes="65013"/>
  </field>

  <field name="CAC-VAL-MNTO">
    <type name="double" size="19" integers="11" decimals="4" sign="no" />
    <fms name="CAC_VAL_MNTO" modifier="FLD" row="9" column="17" picture="99.999.999.999,9999" attributes="1628668"/>
  </field>

  <field name="CAC-COD-MONE">
    <type name="string" size="6"/>
    <fms name="CAC_COD_MONE" modifier="FLD" row="9" column="58" picture="XXXXXX" attributes="65013"/>
  </field>

  <field name="FRM-GLS-MONE">
    <type name="string" size="12"/>
    <fms name="FRM_GLS_MONE" modifier="FLD" row="9" column="67" picture="XXXXXXXXXXXX" attributes="64759"/>
  </field>

  <field name="CAC-VAL-PORC">
    <type name="double" size="8" integers="3" decimals="4" sign="no" />
    <fms name="CAC_VAL_PORC" modifier="FLD" row="10" column="28" picture="999,9999" attributes="1628668"/>
  </field>

  <field name="CAC-COD-COD1">
    <type name="string" size="12"/>
    <fms name="CAC_COD_COD1" modifier="FLD" row="12" column="17" picture="XXXXXXXXXXXX" attributes="65013"/>
  </field>

  <field name="CAC-COD-COD2">
    <type name="string" size="12"/>
    <fms name="CAC_COD_COD2" modifier="FLD" row="12" column="58" picture="XXXXXXXXXXXX" attributes="65013"/>
  </field>

  <field name="FRM-COD-CD12">
    <type name="string" size="24"/>
    <fms name="FRM_COD_CD12" modifier="FLD" row="13" column="17" picture="XXXXXXXXXXXXXXXXXXXXXXXX" attributes="65013"/>
  </field>

  <field name="CAC-COD-COD3">
    <type name="string" size="12"/>
    <fms name="CAC_COD_COD3" modifier="FLD" row="15" column="17" picture="XXXXXXXXXXXX" attributes="65013"/>
  </field>

  <field name="CAC-COD-COD4">
    <type name="string" size="12"/>
    <fms name="CAC_COD_COD4" modifier="FLD" row="15" column="58" picture="XXXXXXXXXXXX" attributes="65013"/>
  </field>

  <field name="FRM-COD-CD34">
    <type name="string" size="24"/>
    <fms name="FRM_COD_CD34" modifier="FLD" row="16" column="17" picture="XXXXXXXXXXXXXXXXXXXXXXXX" attributes="65013"/>
  </field>

  <field name="FRM-GLS-DES1">
    <type name="string" size="20"/>
    <fms name="FRM_GLS_DES1" modifier="FLD" row="18" column="17" picture="XXXXXXXXXXXXXXXXXXXX" attributes="65013"/>
  </field>

  <field name="FRM-GLS-DES2">
    <type name="string" size="20"/>
    <fms name="FRM_GLS_DES2" modifier="FLD" row="18" column="58" picture="XXXXXXXXXXXXXXXXXXXX" attributes="65013"/>
  </field>

  <field name="CAC-GLS-DESC">
    <type name="string" size="40"/>
    <fms name="CAC_GLS_DESC" modifier="FLD" row="19" column="17" picture="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" attributes="65013"/>
  </field>

  <primary>
    <field name="CAC-COD-CPTO"/>
    <field name="DBC-VRF-ICLI"/>
    <field name="DBC-IDC-ICLI"/>
    <field name="CAC-FEC-FINI"/>
    <field name="CAC-HRA-HINI"/>
  </primary>

  <text caption="Concepto:" row="4" column="3" />
  <text caption="IdC     :" row="5" column="3" />
  <text caption="Fecha:" row="5" column="42" />
  <text caption="Hora:" row="5" column="64" />
  <text caption="----------------------------------------------------------------------------" row="6" column="3" />
  <text caption="Vigencia" row="7" column="3" />
  <text caption="Fecha Termino" row="7" column="35" />
  <text caption="Hora" row="7" column="64" />
  <text caption="Monto" row="9" column="3" />
  <text caption="Moneda" row="9" column="45" />
  <text caption="Porcentaje" row="10" column="3" />
  <text caption="Codigo.1" row="12" column="3" />
  <text caption="Codigo.2" row="12" column="45" />
  <text caption="Codigo.1+2" row="13" column="3" />
  <text caption="Codigo.3" row="15" column="3" />
  <text caption="Codigo.4" row="15" column="45" />
  <text caption="Codigo.3+4" row="16" column="3" />
  <text caption="Sub.Desc.1" row="18" column="3" />
  <text caption="Sub.Desc.2" row="18" column="45" />
  <text caption="Descripcion" row="19" column="3" />

</form>
