=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/build/schemaorg_apache_xmlbeans/src/rangedef.xsd
<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema'
           targetNamespace='http://cl/bee/genfrmjava/rangedef/schema'
                     xmlns='http://cl/bee/genfrmjava/rangedef/schema'>

 <!-- ========================================================================================== ==
   == ranges
   == ========================================================================================== -->

 <xsd:element name='ranges'>

  <xsd:complexType>

   <xsd:sequence>
     <xsd:element ref='field' minOccurs='0' maxOccurs='unbounded'/>
   </xsd:sequence>

  </xsd:complexType>

 </xsd:element>

 <!-- ========================================================================================== ==
   == field
   == ========================================================================================== -->

 <xsd:element name='field'>

  <xsd:complexType>

    <xsd:attribute name='name'       type='xsd:string' use='required'/>
    <xsd:attribute name='domain'     type='xsd:string' use='required'/>
    <xsd:attribute name='system'     type='xsd:string' default=''/>
    <xsd:attribute name='registry'   type='xsd:string' default=''/>
    <xsd:attribute name='table'      type='xsd:string' default=''/>
    <xsd:attribute name='validation' type='xsd:string' default=''/>
    <xsd:attribute name='search'     type='xsd:string' default=''/>

  </xsd:complexType>

 </xsd:element>

</xsd:schema>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/domain-range/range_gns.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<ranges xmlns              = "http://cl/bee/genfrmjava/rangedef/schema"
        xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation = "http://cl/bee/genfrmjava/rangedef/schema rangedef.xsd">

  <field name="CST-COD-PRUE" domain="CODPRUE" />
  <field name="CVM-COD-CAMB" domain="CODCAMB" />
  <field name="CVM-COD-CFNC" domain="CODCFNC" system="GNS" registry="CVM" validation="VALCOD" search="BUSTAB" />
  <field name="CVM-COD-CVDT" domain="CODCVDT" system="GNS" registry="CVM" validation="VALCOD" search="BUSTAB" />
  <field name="CVM-COD-CVSN" domain="CODCVSN" system="GNS" registry="CVM" validation="VALCOD" search="BUSTAB" />
  <field name="CVP-COD-PAMB" domain="CODPAMB" system="GNS" registry="CVP" validation="VALCOD" search="BUSTAB" />
  <field name="CVP-COD-PFNC" domain="CODPFNC" system="GNS" registry="CVP" validation="VALCOD" search="BUSTAB" />
  <field name="CVP-COD-PMOD" domain="CODPMOD" system="GNS" registry="CVP" validation="VALCOD" search="BUSTAB" />
  <field name="CVP-COD-PUSR" domain="CODPUSR" system="GNS" registry="CVP" validation="VALCOD" search="BUSTAB" />
  <field name="CVP-COD-PVDT" domain="CODPVDT" system="GNS" registry="CVP" validation="VALCOD" search="BUSTAB" />
  <field name="CVP-COD-UCVT" domain="CODUCVT" system="GNS" registry="CVP" validation="VALCOD" search="BUSTAB" />
  <field name="DBC-COD-BNCO" domain="CODBNCO" />
  <field name="DBC-COD-OFIC" domain="CODOFIC" />
  <field name="DBC-COD-USER" domain="CODUSER" />
  <field name="DBC-MSC-SEXO" domain="MSCSEXO" />
  <field name="DCP-COD-USUA" domain="CODUSUA" />
  <field name="DCP-IND-ECIC" domain="INDECIC" />
  <field name="DCP-IND-ECIV" domain="INDECIV" />
  <field name="ENT-COD-TENT" domain="CODTENT" system="GNS" registry="ENT" validation="VALCOD" search="BUSTAB" />
  <field name="ENT-GLS-TPRO" domain="GLSTPRO" system="GNS" registry="ENT" validation="VALCOD" search="BUSTAB" />
  <field name="FRM-COD-CLRP" domain="PANCLRP" />
  <field name="FRM-COD-CLRV" domain="PANCLRV" />
  <field name="FRM-COD-CLSE" domain="CODCLSE" system="GNS" registry="BAT" />
  <field name="FRM-COD-CMND" domain="CODLCLX" system="GNS" registry="TAB" validation="VALCOD" search="BUSTAB" />
  <field name="FRM-COD-DEST" domain="CODDEST" system="GNS" registry="BAT" />
  <field name="FRM-COD-FORM" domain="CODFORM" system="GNS" registry="BAT" />
  <field name="FRM-COD-FST1" domain="CODFST1" />
  <field name="FRM-COD-LGMG" domain="CODLGMG" system="GNS" registry="TAB" validation="VALCOD" search="BUSTAB" />
  <field name="FRM-COD-LGMM" domain="CODLGMM" system="GNS" registry="TAB" validation="VALCOD" search="BUSTAB" />
  <field name="FRM-COD-LGMV" domain="CODLGMV" system="GNS" registry="TAB" validation="VALCOD" search="BUSTAB" />
  <field name="FRM-COD-SISG" domain="CODLSLX" system="GNS" registry="TAB" validation="VALCOD" search="BUSTAB" />
  <field name="FRM-COD-TCLA" domain="PANTCLA" />
  <field name="FRM-COD-TFUN" domain="PANTFUN" />
  <field name="FRM-COD-UCNX" domain="CODUSER" />
  <field name="FRM-IND-IDEL" domain="INDIDEL" system="GNS" registry="BAT" />
  <field name="FRM-IND-IGIA" domain="INDIGIA" system="GNS" registry="BAT" />
  <field name="FRM-IND-RRPT" domain="INDRRPT" system="GNS" />
  <field name="FRM-IND-SORT" domain="INDSINO" system="GNS" registry="RPR" />
  <field name="IDD-COD-GRPO" domain="IDDGRPO" system="GNS" registry="IDD" />
  <field name="IDD-COD-SIST" domain="CODSIST" system="GNS" registry="IDD" />
  <field name="IDD-COD-TENT" domain="IDDTENT" system="GNS" registry="IDD" />
  <field name="ITK-COD-RESP" domain="CODCRESP" system="GNS" registry="SRT" />
  <field name="ITK-COD-SIST" domain="CODSIST" system="GNS" registry="SIS" />
  <field name="ITK-IND-RESP" domain="ITKIRESP" system="GNS" registry="IRT" />
  <field name="MNU-COD-AMCM" domain="CODAMPA" system="GNS" registry="MNU" validation="VALCOD" />
  <field name="MNU-COD-AMHD" domain="CODAMPA" system="GNS" registry="MNU" validation="VALCOD" />
  <field name="MNU-COD-AMPG" domain="CODAMPA" system="GNS" registry="MNU" validation="VALCOD" />
  <field name="MNU-COD-ASCR" domain="CODASCR" system="GNS" registry="MNU" validation="VALCOD" />
  <field name="MNU-COD-INST" domain="CODINST" system="GNS" registry="MNU" validation="VALCOD" search="NO" />
  <field name="MNU-COD-MSAL" domain="CODMSAL" system="GNS" registry="MNU" validation="VALCOD" />
  <field name="MNU-COD-TCTL" domain="CODTCTL" />
  <field name="MNU-COD-TFUN" domain="CODTFUN" system="GNS" registry="MNU" validation="VALCOD" search="NO" />
  <field name="MNU-COD-TINF" domain="CODTINF" />
  <field name="MNU-COD-UIDD" domain="CODUIDD" system="GNS" registry="MNU" validation="VALCOD" />
  <field name="MNU-IND-CONF" domain="INDSINO" system="GNS" registry="MNU" validation="VALCOD" search="NO" />
  <field name="MNU-IND-EXGL" domain="INDSINO" system="GNS" registry="MNU" validation="VALCOD" search="NO" />
  <field name="MNU-IND-IPRV" domain="INDIPRV" system="GNS" registry="MNU" validation="VALCOD" search="NO" />
  <field name="OCK-COD-ACCI" domain="CODACCI" system="GNS" registry="OCK" validation="VALCOD" search="BUSTAB" />
  <field name="OCK-COD-AOCK" domain="CODUSER" system="TAB" validation="VALUSR" search="BUSUSR" />
  <field name="OCK-COD-CONS" domain="CODCONS" system="GNS" registry="OCK" validation="VALCOD" search="BUSTAB" />
  <field name="OCK-COD-PENT" domain="CODPENT" system="GNS" registry="OCK" validation="VALCOD" search="BUSTAB" />
  <field name="OCK-MSC-STAT" domain="MSCSTAT" system="GNS" registry="OCK" validation="VALCOD" search="BUSTAB" />
  <field name="OPC-COD-BANC" domain="CODBANC" />
  <field name="OPC-COD-OFIA" domain="CODOFIA" />
  <field name="OPC-MSC-SEXC" domain="MSCSEXC" />
  <field name="PAN-COD-CLRP" domain="PANCLRP" />
  <field name="PAN-COD-CLRV" domain="PANCLRV" />
  <field name="PAN-COD-TCLA" domain="PANTCLA" />
  <field name="PAN-COD-TFUN" domain="PANTFUN" />
  <field name="PCK-COD-APCK" domain="CODUSER" system="TAB" registry="USR" validation="VALUSR" search="BUSUSR" />
  <field name="PCK-COD-AVRF" domain="CODUSER" system="TAB" registry="USR" validation="VALUSR" search="BUSUSR" />
  <field name="PCK-COD-FENT" domain="CODPENT" system="GNS" registry="PCK" validation="VALCOD" search="BUSTAB" />
  <field name="PCK-COD-PAMB" domain="CODPAMB" system="GNS" registry="PCK" validation="VALCOD" search="BUSTAB" />
  <field name="PCK-COD-PENT" domain="CODPENT" system="GNS" registry="PCK" validation="VALCOD" search="BUSTAB" />
  <field name="PCK-COD-PFNC" domain="CODPFNC" system="GNS" registry="PCK" validation="VALCOD" search="BUSTAB" />
  <field name="PCK-COD-SENT" domain="CODPENT" system="GNS" registry="PCK" validation="VALCOD" search="BUSTAB" />
  <field name="PCK-MSC-STAT" domain="PCKSTAT" system="GNS" registry="PCK" validation="VALCOD" search="BUSTAB" />
  <field name="PDP-COD-BNCO" domain="CODBNCO" />
  <field name="PDP-COD-CART" domain="CODCART" />
  <field name="PDP-COD-CMND" domain="CODCMND" />
  <field name="PDP-COD-CNAL" domain="CODCNAL" />
  <field name="PDP-COD-GRPO" domain="CODGRPO" />
  <field name="PDP-COD-MODO" domain="CODMODO" />
  <field name="PDP-COD-MRCA" domain="CODMRCA" />
  <field name="PDP-COD-SIST" domain="CODSIST" />
  <field name="PDP-COD-TDPU" domain="CODTDPU" />
  <field name="PDP-IND-RESP" domain="INDRESP" />
  <field name="PRU-COD-CDGO" domain="CODCDGO" system="GNS" registry="PRU" />
  <field name="PRU-IND-INDI" domain="INDINDI" system="GNS" registry="PRU" />
  <field name="PRU-MSC-MSCL" domain="MSCMSCL" system="GNS" registry="PRU" />
  <field name="PRU-XXX-CDGO" domain="XXXCDGO" system="GNS" registry="PRU" />
  <field name="RCI-COD-CNAL" domain="CODCNAL" />
  <field name="RCI-COD-MODO" domain="CODMODO" system="GNS" registry="TAB" validation="VALCOD" search="BUSTAB" />
  <field name="RCI-COD-USER" domain="CODUSER" />
  <field name="REL-COD-TEN1" domain="CODTENT" system="GNS" registry="REL" validation="VALCOD" search="BUSTAB" />
  <field name="REL-COD-TEN2" domain="CODTENT" system="GNS" registry="REL" validation="VALCOD" search="BUSTAB" />
  <field name="REL-GLS-MODO" domain="GLSMODO" system="GNS" registry="REL" validation="VALCOD" search="BUSTAB" />
  <field name="RF1-COD-CMND" domain="RF1CMND" system="GNS" registry="RF1" validation="VALCOD" search="BUSTAB" />
  <field name="RUG-COD-GRPO" domain="CODGRPO" />
  <field name="RUG-COD-USER" domain="CODUSER" validation="VALUSR" search="BUSUSR" />
  <field name="RUG-COD-VIGE" domain="CODVIGE" />
  <field name="RUG-IND-CIGE" domain="INDVIGE" />
  <field name="RUG-IND-VIGE" domain="INDVIGE" />
  <field name="SDS_COD_SSDS" domain="CODSSDS" system="GNS" />
  <field name="TAB-IND-VIGE" domain="MSCVIGE" />
</ranges>

=== Osvaldo-Gutierrez/BeeFRM-workspace/BeeFRM/data/domain-range/range_tab.xml
<?xml version = "1.0" encoding = "ISO-8859-1" ?>

<ranges xmlns              = "http://cl/bee/genfrmjava/rangedef/schema"
        xmlns:xsi          = "http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation = "http://cl/bee/genfrmjava/rangedef/schema rangedef.xsd">

  <field name="ACT-IND-VIGE" domain="INDVIGE" system="TAB" registry="ACT" />
  <field name="BCO-IND-VIGE" domain="INDVIGE" system="TAB" registry="BCO" />
  <field name="COM-COD-DPTO" domain="CODDPTO" system="TAB" registry="DPT" />
  <field name="COM-COD-PAIS" domain="CODPAIS" system="TAB" registry="PAI" />
  <field name="COM-COD-PRVC" domain="CODPRVC" system="TAB" registry="PRV" />
  <field name="COM-COD-REGI" domain="CODREGI" system="TAB" registry="REG" />
  <field name="COM-IND-VIGE" domain="INDVIGE" system="TAB" registry="COM" />
  <field name="CYA-IND-TCYA" domain="CODCYA" />
  <field name="FRM-IND-LOGA" domain="INDLOGA" system="GNS" registry="TAB" />
  <field name="IVB-COD-DPTO" domain="CODDPTO" system="TAB" registry="DPT" />
  <field name="IVB-COD-TTAB" domain="CODTTA1" system="TAB" registry="IVB" />
  <field name="IVB-IND-VIGE" domain="INDVIGE" system="TAB" registry="IVB" />
  <field name="OFI-COD-COMU" domain="CODCOMU" system="TAB" />
  <field name="OFI-COD-PLZA" domain="CODPLZA" system="TAB" />
  <field name="OPC-COD-COOC" domain="CODCOOC" />
  <field name="OPC-COD-TTRN" domain="CODCNL" />
  <field name="OPC-COD-VCOC" domain="CODVCOC" />
  <field name="PAI-IND-VIGE" domain="INDVIGE" system="TAB" registry="PAI" />
  <field name="PZA-COD-BNCO" domain="CODCBCO" system="TAB" registry="PZA" />
  <field name="PZA-IND-VIGE" domain="INDVIGE" system="TAB" registry="PZA" />
  <field name="ROP-COD-FORM" domain="TABFOR" />
  <field name="ROP-COD-TCAP" domain="TABCAP" />
  <field name="ROR-COD-CNAL" domain="CODCNL" />
  <field name="ROR-COD-COOC" domain="CODCOOC" />
  <field name="ROR-COD-VCOC" domain="CODVCOC" />
  <field name="ROR-IND-TCYA" domain="CODCYA" />
  <field name="SVC-IND-VIGE" domain="INDVIGE" system="TAB" registry="SVC" />
  <field name="TAB-COD-CTAB" domain="CODCTAB" system="TAB" registry="TAB" />
  <field name="TIO-IND-ACPA" domain="INDACPA" system="TAB" registry="TIO" />
  <field name="TIO-IND-TCOL" domain="INDTCOL" system="TAB" registry="TIO" />
  <field name="TIO-IND-VIGE" domain="INDVIGE" system="TAB" registry="TIO" />
  <field name="USR-COD-AGES" domain="CODAGES" registry="USR" />
  <field name="USR-COD-BNCA" domain="CODBNCA" system="TAB" registry="USR" />
  <field name="USR-COD-CNEG" domain="CODCNEG" system="TAB" registry="USR" />
  <field name="USR-COD-CUSR" domain="CODCUSR" system="TAB" registry="USR" />
  <field name="USR-COD-OFUS" domain="CODOFIC" registry="USR" />
  <field name="USR-COD-PLAT" domain="CODPLAT" system="TAB" registry="USR" />
  <field name="USR-COD-REGL" domain="CODREGL" system="TAB" registry="USR" />
  <field name="USR-COD-TEJE" domain="CODTEJE" system="TAB" registry="USR" validation="VALCOD" search="BUSTAB" />
  <field name="USR-COD-TTAB" domain="CODTTAB" system="TAB" registry="USR" />
  <field name="USR-COD-UBIC" domain="CODUBIC" system="TAB" registry="USR" />
  <field name="USR-IND-VIGE" domain="INDVIGE" system="TAB" registry="USR" />
  <field name="VLR-IND-VIGE" domain="INDVIGE" system="TAB" registry="VLR" />
  <field name="WFC-COD-ACTC" domain="CODACT" />
  <field name="WFC-COD-CFMN" domain="CODVCOC" />
  <field name="WFC-COD-CVTE" domain="CODVCOC" />
  <field name="WFC-COD-EBCI" domain="CODTDU" />
  <field name="WFC-COD-EBCS" domain="CODTDU" />
  <field name="WFC-COD-OFCV" domain="CODOFIC" />
  <field name="WFC-COD-PTRF" domain="CODPTR" />
  <field name="WFC-COD-SBCI" domain="CODOFIC" />
  <field name="WFC-COD-SBCS" domain="CODOFIC" />
  <field name="WFC-MSC-STAT" domain="CODSTT" />
</ranges>
